### ISSUE TITLE
Online Demo! is not working

### ISSUE THREAD

**Issue by LeeHyungGeun** [Tencent/omi#121]
I am not sure whether it is a github issue, or not.
**Online Demo!** is not working.
- URL: https://tencent.github.io/omi/assets/
- Page Show: "GitHub Pages is temporarily down for maintenance."

**Comment by dntzhang** [comment]
I just tried. It's okay.

**Comment by dntzhang** [comment]
https://tencent.github.io/omi/assets/index.html

**Comment by LeeHyungGeun** [comment]
@dntzhang It looks was a temporary github error. Thanks and it is working to me as well.
