### ISSUE TITLE
mobx感觉并不是那么好用，omi-mobx可以改为omi-redux吗？

### ISSUE THREAD

**Issue by zwl1619** [Tencent/omi#133]
mobx感觉并不是那么好用，omi-mobx可以改为omi-redux吗？

**Comment by dntzhang** [comment]
不可以。我个人不爱 redux。如果社区可以贡献 omi redux，我也不会反对。欢迎pr

**Comment by jpy920718** [comment]
mobx 用起来还是挺爽的

**Comment by LeeHyungGeun** [comment]
@dntzhang 我可以知道为什么不爱Redux吗？

**Comment by dntzhang** [comment]
@LeeHyungGeun 写起来麻烦，过度设计

**Comment by ddzy** [comment]
@dntzhang 有考虑一下dva么, 觉得还可以

**Comment by dntzhang** [comment]
@ddzy 看了下一个 counter 写了 50 行代码。不知道为啥就是爱不上那种写法，我不会考虑。但是社区pr进来我会合进去。或者社区有人开发我也可以挂链接。但是自己开发是不可能，因为不爱。

**Comment by zwl1619** [comment]
我感觉omi对标umi就好了。当然有可能就是，因为名字很像了。

**Comment by ddzy** [comment]
紧跟大佬步伐

**Comment by ddzy** [comment]
紧跟大牛步伐!
