### ISSUE TITLE
在本组件内更新store后，本组件内读取store都是更新的，没有按需更新

### ISSUE THREAD

**Issue by ok111net** [Tencent/omi#186]
`@tag('el-store-test')
class LoadingElement extends Element {
  static get data() {
    //如果你用了 store，这个只是用来声明依赖，按需 Path Updating
    return {
      name:''
    }
  }
  
  onClick=()=>{
    this.store.data.test.b[2]='12333';
    this.update();
  };
  
  render=(props,store)=>〈h1 onClick={this.onClick}>{store.test.b[2]}</h1〉;
}`

这样子在本组件内改变store,不管上面data里是否订阅了store.test.b,它都是会更新的,而不是象在其它组件内是按需更新的

**Comment by dntzhang** [comment]
这不算bug吧

**Comment by dntzhang** [comment]
this.update就是更新自己。你交给store最后也是调用update。只有this.store.update才是按需更新

**Comment by ok111net** [comment]
对，用this.store.update可以了，是我搞混了，关闭了吧
