### ISSUE TITLE
#资源翻译# 

### ISSUE THREAD

**Issue by eyea** [Tencent/omi#200]
已初步翻译: Shadow Dom In Depth, 如何支持？

**Comment by dntzhang** [comment]
教程目录加个文件 然后pull request。 赞👍

**Comment by eyea** [comment]
好的 请斧正~

**Comment by dntzhang** [comment]
真棒！

**Comment by eyea** [comment]
@dntzhang 昨天原文作者要求在翻译前面添加他的项目链接，所以麻烦合一个 [PR](https://github.com/Tencent/omi/pull/205) 😄 (我之前翻译没考虑到作者这个需求，抱歉)

**Comment by dntzhang** [comment]
冲突了~~  修改下再次 pr
