### ISSUE TITLE
  请问:wx.showToast和wx.showLoading这些api都无法使用吗？

### ISSUE THREAD

**Issue by baixiaohan** [Tencent/omi#209]
Unhandled Rejection (TypeError): wx.showToast is not a function
HTMLElement._callee$
src/mp/pages/index/index.js:43
  40 | // wx.showLoading({
  41 | //   mask:true
  42 | // });
> 43 | wx.showToast({
  44 |   'title':'',
  45 |   icon:'loading'
  46 | });

**Comment by dntzhang** [comment]
是的，没法使用。不过 omi-mp 快要支持了~~~

**Comment by baixiaohan** [comment]
感谢作者的回复。
近期不支持的话，自己先用自定义组件临时搞一下吧~~~~
