### ISSUE TITLE
gzip -9 omi.min.js is larger than 4kb

### ISSUE THREAD

**Issue by LongJohnCoder** [Tencent/omi#210]
4kb gzipped claim in readme and github project description should be updated to current reality of greater than 6kb gzipped.

**Comment by dntzhang** [comment]
Got it.

**Comment by dntzhang** [comment]
fixed~

**Comment by LongJohnCoder** [comment]
Part of it was missed in the readme. "Why Omi? Tiny size. (4kb gzipped)"

**Comment by dntzhang** [comment]
DONE
