### ISSUE TITLE
omi-mp watch 监听不到文件变化

### ISSUE THREAD

**Issue by loo41** [Tencent/omi#213]
https://github.com/Tencent/omi/blob/81c5e196b3b40c9acc55b5f4c79eff141c5915e8/packages/omi-mp/gulpfile.js#L203

- omi-mp下在非 ASCII characters 下监听不到变化
- 看了下 [ issues](https://github.com/floatdrop/gulp-watch/issues/306) 说是修复此功能
- 5.0.1下还未修复 [PR](https://github.com/floatdrop/gulp-watch/pull/313)

#212

**Comment by dntzhang** [comment]
赞，合了
