### ISSUE TITLE
在omi-mp-create里我连续用10次this.oData或者一次setData一次更新10个属性，哪个性能更高

### ISSUE THREAD

**Issue by hunshikan** [Tencent/omi#226]
this.oData.a = 1;
this.oData.b = 2;
this.oData.c = 3;
this.oData.d = 4;
......

this.setData({
    a:1,
    b:2,
    c:3,
    d:4,
    .....
})

**Comment by dntzhang** [comment]
omi-mp-create 数据变更自动计算最短路径性能大部分场景都很高，但单纯从这个 case 来看，下面的高。但是 omi-mp-create 在考虑要不要合并多次数据变更导致的 setData..

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/issues/226
