### ISSUE TITLE
[omi-mp] bindtap和bindtouchstart等事件内不能setData?

### ISSUE THREAD

**Issue by bladewhite** [Tencent/omi#232]
转换到h5页面之后，tap和touch的事件内既不能访问this.data也不能this.setData，这是什么原因呢？

另，omi-mp有达到实用级别的小程序转h5的案例或者demo吗？
开发好的稍微复杂些的小程序，转换起来障碍重重，所以疑问目前转h5的功能是否仅仅只是预览阶段而不适合实际应用？要用在生产的环境的话更适合拿omi进行原生web开发？或者转h5功能近期有完善的计划吗？

谢谢！

**Comment by dntzhang** [comment]
我先看下你遇到的 
bug，再回答你下面的问题~~

**Comment by dntzhang** [comment]
```js
  myEventHandler: function (evt) {
  console.log(this.data)
    this.setData({
      logs:['111','222']
    })
    console.log(this)
    //output -> dntzhang
    console.log(evt.detail.name)
  }
```

刚那omi-mp 项目试了是ok的，你可能没有更新到最新的 omi-mp。

1.案例是有的，但是限制 readme 里已经下了，都必须遵守
2.微信支付内部许多项目都在使用，但是大部分项目是从零开始开发，使用omi-mp同时开发小程序和H5
3.完善计划不知道是指什么，但是你看 omi-mp 的提交记录可以看到，一直在 fix bug 和优化

**Comment by bladewhite** [comment]
omi版本是3.0.21

<img width="346" alt="qq20181222-113009 2x" src="https://user-images.githubusercontent.com/20840262/50370186-11706280-05dd-11e9-9037-d52be2985811.png">

另外setData不支持回调函数也是版本问题吗？

**Comment by dntzhang** [comment]
回调目前不支持，用最新的cli
