### ISSUE TITLE
[omi-mp-create] 对对象造成污染？

### ISSUE THREAD

**Issue by SuperHuangXu** [Tencent/omi#234]
```js
// .......
util.getCache("info").then(({ data }) => {
        // 这里的data对象也会被监听？？？
        console.log(data);
      })
```

**Comment by SuperHuangXu** [comment]
![tim 20181222005238](https://user-images.githubusercontent.com/14816052/50354908-f6273800-0587-11e9-8b81-46a6d382b182.png)

可不可以不让`$observeProps`出现在对象中？

**Comment by dntzhang** [comment]
这个我看怎么优化~

**Comment by WozHuang** [comment]
我把obaa中的代码稍稍改了一下 `$observeProps` 就不会出现在页面的data中：

把其中所有的直接赋值

```js
target.$observeProps = {}
```
都修改为不可以枚举的
```js
Object.defineProperty(target, '$observeProps', {
  configurable: true,
  enumerable: false,
  writable: true,
  value: {}
})
```

就没有出现在AppData里了

![image](https://user-images.githubusercontent.com/22727100/50506560-87306e80-0ab4-11e9-922a-ae00c85e5729.png)

这个时候 `this.data` 里面还是带着个`$observeProps`，如果需要完全无污染的对象的话就深拷贝一下
 ```js
JSON.parse(JSON.stringfy(this.data))
```

（这样应该算解决问题了？）

**Comment by dntzhang** [comment]
算！ pr~~~ 快~
