### ISSUE TITLE
omi-mp-create 如何初始化页面的data

### ISSUE THREAD

**Issue by ivanlee93** [Tencent/omi#245]
比如提交一个表单后直接Object.assign(this.$data, this.$options.data())重置页面data
上面是mpvue的方式，小程序有类似的方式吗

**Comment by dntzhang** [comment]
Object.assign(this.oData, xxxx)

**Comment by ivanlee93** [comment]
> Object.assign(this.oData, xxxx)

我用的是中心化的编写方式

**Comment by dntzhang** [comment]
Object.assign(this.store.data, xxxx)

**Comment by ivanlee93** [comment]
还有一个问题，中心化的方式没有oData，我更改页面的私有变量，必须setData吗？强迫症想统一一下

**Comment by dntzhang** [comment]
是的。
