### ISSUE TITLE
计算属性

### ISSUE THREAD

**Issue by transtone** [Tencent/omi#253]
怎么在 omi-mp-create 里实现类似 vue computed（计算属性）？

https://github.com/b5156/wxapp-computed/

这里的方案可以借鉴进来吗？

像 mobx 里 computed 就是自带的：https://cn.mobx.js.org/refguide/computed-decorator.html

**Comment by transtone** [comment]
原来小程序官方有扩展：
https://github.com/wechat-miniprogram/computed

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/commit/986ae3f06348ec837ce9a9dd6ae877252d03978d

**Comment by dntzhang** [comment]
已支持，试试~~

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/commit/dfa70957aeb05061fa1e3be3a6f73a75250a3823

**Comment by transtone** [comment]
函数属性在中心化api里无效。 @dntzhang

**Comment by transtone** [comment]
非常感谢磊哥的及时更新。
在 omi-mp-create 示例的 other.js 里，加入 
``` js
create(store, {
  data: {
    motto: 'Hello World',
    reverseMotto() {
      return this.motto
        .split('')
        .reverse()
        .join('')
    }
  },
})
```
后发现：
1. 写在store里的函数属性是有效的。
2. reverseMotto写在 other.js 里无效。
3. 写在 other.js 里的 motto 其实是全局变量，和写在 store.js 里是一样，在所有引入了store的页面都可以访问到。

那么有两个疑问：
1. 所有中心化api的页面，就不再有自己的私有data了，数据岂不很乱？
2. 既然 data 不是私有的，为何这种写法无效？

**Comment by dntzhang** [comment]
看了下 reverseMotto 在 stringify的时候丢了，嫌中心化数据混乱请使用去中心化 API。

**Comment by transtone** [comment]
> 看了下 reverseMotto 在 stringify的时候丢了，嫌中心化数据混乱请使用去中心化 API。

好的，谢谢回复。在修复了吗？
