### ISSUE TITLE
再提个建议

### ISSUE THREAD

**Issue by myliweihao** [Tencent/omi#256]
据说omi打磨3年了，但这个框架教程文档很少很少，只有官方一点点介绍。
个人想法，一个框架要流行，前提要有很多人用，很多人用的前提是易入门开发，并且教程比较丰富，据观察视频教程更容易理解。（虽然大神都希望追求效率看文档，不愿花时间看视频，但这类大神比例很少很少），所以建议吸引初中级开发者使用框架，当不断有人使用时，就会有人遇到需求，大佬们就可以筛选开发者一线需求，进行框架大迭代。
说那么多就是本人比较懒，希望官方出一套视频教程，介绍技术点和简单的脚手架项目实战。

**Comment by dntzhang** [comment]
说再多也没用...  没有时间。

**Comment by dntzhang** [comment]
我要写的框架的 todo list 已经列到了 2022 年了，还视频教程，根本没有时间。

**Comment by XboxYan** [comment]
其实框架已经尽可能像React那些靠拢了，只要看一下官方的几个示例基本上就能上手了，还需要什么教程

**Comment by stys35** [comment]
根本不需要视频教程，这么简单的框架还要啥视频教程，有个大概的文档就可以了
