### ISSUE TITLE
TS2425 error in typescript

### ISSUE THREAD

**Issue by kelvindc** [Tencent/omi#257]
TS2425: Class 'WeElement<HelloOmiProps, {}>' defines instance member property 'css', but extended class '(Anonymous class)' defines it as instance member function.

![image](https://user-images.githubusercontent.com/2488106/51793926-30c56580-2203-11e9-9d1f-9c5d53508314.png)

**Comment by dntzhang** [comment]
Fixed, please using the latest omi and omio~~! many thanks!~~
