### ISSUE TITLE
关于中心化和去中心化

### ISSUE THREAD

**Issue by DocBug** [Tencent/omi#261]
初次发现这个小巧的框架，很是喜欢，就是初次有点不懂运用。
去中心化，似乎就没有了整个的数据仓库了。
中心化，就把每个页面的所有data都中心化了。
有没有办法，我只想部分数据中心化，其他的去中心化呢

**Comment by dntzhang** [comment]
用去中心化的 store

**Comment by DocBug** [comment]
试了，第一个有用，第二个页面就没有自动赋值到 store 内指定的值上面了。

**Comment by DocBug** [comment]
似乎在store.js 里面定义的数据并没有赋值到每个页面的store上面呢。
粗略的看了下源码，好像没看到对store有其他操作的样子呢？

**Comment by dntzhang** [comment]
既有自己的data又有全局store可以:中心化api可以搭配  create.Component(option)

**Comment by DocBug** [comment]
目前，我使用去中心化，并在 store.js 中放入 一个arr: [1,2,3]
在 create.Page({
    store: {
        arr: []
    }
})
不能正常获取到值，我想这种效果的，是可以的吗？

**Comment by dntzhang** [comment]
不可以

**Comment by dntzhang** [comment]
create.Page({
store: {
arr: [1,2,3]
}
})

**Comment by dntzhang** [comment]
或者 import  store from store.js

**Comment by DocBug** [comment]
我试过这个
import store from store.js
create.Page({
    data: {
        ...store.data
    }
})
然后在其他页面update  store中的数据，
返回后，页面数据有更新，视图没有更新

**Comment by xmsz** [comment]
刚从westore转来，的确有些不理解
如果我把user_info定义为全局数据，那么在去中心化里，如果保持这个全局属性。

如果是中心化的方式，那么和westore是不是相同

**Comment by dntzhang** [comment]
* 去中心化的 store 改成了 context 更好理解
* 中心化的 store 挂在所有 this.data.store 下，wxml 里需要使用 `store.`  前缀，这样隔离了 store.data 和 data

**Comment by dntzhang** [comment]
* https://github.com/Tencent/omi/commit/03aa56e3201aa7be0c95053725564f445c0722c3
* https://github.com/Tencent/omi/commit/67b5fc1b20354005cca8f72bc9252060db61e40b

**Comment by dntzhang** [comment]
任何问题欢迎反馈～～
