### ISSUE TITLE
关于web-components的通用性

### ISSUE THREAD

**Issue by XboxYan** [Tencent/omi#263]
起初看到这个工程的时候，以为是用`web-components`的方式来打造各种原生组件，以便在任何地方都能像原生`div`、`input`这些标签使用。如果是这样的话，那么不管是原生项目，还是`vue`、`react`这些也能直接使用。
然而，`omi`好像也是构造了自己的一套系统，虽然说是用`web-components`实现的，但是原理和`react`这些也差不多，只是多了一种实现方式，也无法作为`web`通用组件，不受限于各大组件库。
怎么说呢，还是希望有那么一天。

**Comment by dntzhang** [comment]
这天已经到来。
