### ISSUE TITLE
Omi 案例征集

### ISSUE THREAD

**Issue by dntzhang** [Tencent/omi#266]
**你还可以主动向 Omi 提交 PR 把你的项目放到 Omi README 的案例展示中，或者回复此条 issue 提交案例名和二维码或 url。**

```js
name: 案例名
url: 二维码图片或链接地址
```

**Comment by XboxYan** [comment]
正在做一个原生web components组件库，将来会考虑用Omi来重构

[项目地址](https://github.com/XboxYan/XYUI)

[在线预览](https://xboxyan.codelabo.cn/XYUI)

**Comment by dntzhang** [comment]
哈，不错。可以参考 [omim](https://tencent.github.io/omi/packages/omim/docs/build/cn.html) 架构重构

**Comment by XboxYan** [comment]
原生语法其实还行，不用依赖任何环境，也不需要打包编译，就是操作`innerHTML`相对麻烦，写起来有些啰嗦，属性变化需要手动去更新。
