### ISSUE TITLE
能开发百度等等其他小程序吗

### ISSUE THREAD

**Issue by aiplat** [Tencent/omi#268]
omi的出现，是不是因为wepy的bug太多要摒弃wepy?
但是omi只能开发微信小程序吧，并不能同时打包成百度、支付宝、头条小程序。

**Comment by andypinet** [comment]
建议野心大一点 支持支付宝小程序

**Comment by aiplat** [comment]
> 
> 
> 建议野心大一点 支持支付宝小程序

我说的是百度等等，不是只是百度。描述中包含微信、百度、支付宝、头条小程序。

**Comment by marsprince** [comment]
你觉得企鹅会这么大度？
