### ISSUE TITLE
omi支持async/await语法吗

### ISSUE THREAD

**Issue by Andark** [Tencent/omi#271]
我在Omi的代码中使用了async/await，但是收到了如下异常：
sdk uncaught third Error 
regeneratorRuntime is not defined。

看到regeneratorRuntime，我理解omi中是不是默认不支持async/await的，不知道是不是这样？如果目前还不支持，那有计划加入对async和await的支持吗？

**Comment by dntzhang** [comment]
我现在看下。

**Comment by dntzhang** [comment]
刚试了下 omi cli创建的项目是可以的

**Comment by dntzhang** [comment]
![11ac5842555685bc941647b9e2f93f54](https://user-images.githubusercontent.com/7917954/53731833-fc566080-3eb6-11e9-81b3-56f6e55e1fa4.jpg)
![1f15654f58f557c408ccb20862d13694](https://user-images.githubusercontent.com/7917954/53731844-ffe9e780-3eb6-11e9-8481-3b75c0d704a4.jpg)
