### ISSUE TITLE
本地图片无法载入

### ISSUE THREAD

**Issue by jzsjiale** [Tencent/omi#278]
在src/pages/index/index.tsx文件中使用image组件，以如下方法引入图片：
`<image  src="../../assets/images/my/liulan.png"></image>`
图片无法正常加载。
图片放置路径为：src/assets/images/my/liulan.png，
小程序端提示错误为：
`Failed to load local image resource /assets/images/my/liulan.png 
 the server responded with a status of 404 (HTTP/1.1 404 Not Found) `

使用的omi最新版本。
引用路径应该是对的，图片拷贝不过去，请问是什么问题呢？放到images根目录也引用不过去，只有app.tsx里的tabBar下引用图片可以加载。

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/commit/757ba847506df994a03c989b536c99a977290869
