### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by a805883237** [Tencent/omi#280]
```
$ sudo npm i omi-cli -g
```
**Installation failed**

```
npm ERR! path /Users/rain/.nvm/versions/node/v7.10.0/lib/node_modules/node/lib/node_modules/node/lib/node_modules/omi-cli/node_modules/abab
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/Users/rain/.nvm/versions/node/v7.10.0/lib/node_modules/node/lib/node_modules/node/lib/node_modules/omi-cli/node_modules/abab'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rain/.npm/_logs/2019-03-13T04_35_26_961Z-debug.log
```

```
$omi
zsh: command not found: omi
```

**Comment by a805883237** [comment]
node version  : v9.8.0

**Comment by dntzhang** [comment]
npx试试

**Comment by tangcaiyue** [comment]
npm i omi-cli
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tangna/.npm/_logs/2019-03-15T08_01_06_939Z-debug.log
tangnadeMacBook-Pro:omi tangna$ npm install omi-cli
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tangna/.npm/_logs/2019-03-15T08_01_19_132Z-debug.log
tangnadeMacBook-Pro:omi tangna$ npx i omi-cli -g
npx: 1 安装成功，用时 2.554 秒
找不到命令：i
tangnadeMacBook-Pro:omi tangna$ omi
-bash: omi: command not found
tangnadeMacBook-Pro:omi tangna$ npx omi-cli -g
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tangna/.npm/_logs/2019-03-15T08_03_37_134Z-debug.log
安装 omi-cli@latest 失败，错误代码：1

**Comment by tangcaiyue** [comment]
npm install omi-cli
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npx omi-cli init my-app
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npm -v
6.4.1
node -v
v8.15.0
是不是版本低了？

**Comment by dntzhang** [comment]
模板地址

https://github.com/Tencent/omi/tree/master/packages/omi-cli/template
https://github.com/omijs

不行的话直接下载下来用

**Comment by tangcaiyue** [comment]
我把node版本 换为v9.8.0，然后用npx omi-cli init-p my-app  这个命令可以了

**Comment by a805883237** [comment]
> 我把node版本 换为v9.8.0，然后用npx omi-cli init-p my-app 这个命令可以了

---------------------

我这也可以，不过还是没有omi 命令

**Comment by dntzhang** [comment]
嗯，cli 没装成功是没有 omi 命令的
