### ISSUE TITLE
使用omiu 编译时遇到的问题，求助

### ISSUE THREAD

**Issue by jzsjiale** [Tencent/omi#281]
在使用omiu开发小程序时，编译出来小程序控制台报错，omiu文档里面有这样一句解释，node modules 下的 omiu 组件都是 E6+,你需要把 node modules 下的 js 也设置成经过 babel 或 ts 编译才能正常跑起来

请问，这个是该如何配置的呢？谢谢

**Comment by dntzhang** [comment]
omiu 不能用在小程序

**Comment by jzsjiale** [comment]
好吧，谢谢
