### ISSUE TITLE
建议建议

### ISSUE THREAD

**Issue by lsw1990** [Tencent/omi#282]
能够增加一个页面级别的混入呢？页面级别的路由钩子，小程序omix的

**Comment by dntzhang** [comment]
不是很懂，API 书写方式列一下。

**Comment by lsw1990** [comment]
@dntzhang 类似vue的路由钩子，先执行钩子函数等一系列的，之后再进行page页面的，当然小程序不能阻塞，类似这个人写的混入机制，https://github.com/wendux/grace

**Comment by lsw1990** [comment]
@dntzhang 这两个功能没有计划会加入？

**Comment by dntzhang** [comment]
暂时没有人力投入这块。
