### ISSUE TITLE
请问如何在自定义组件的install方法里，接收并验证传递给组件的props参数呢？

### ISSUE THREAD

**Issue by jzsjiale** [Tencent/omi#284]
从pages里的页面调用 自定义组件，并传递 参数，在自定义组件的render中可以直接使用 {this.props.isshow}  这种方式来获取变量值，那么请问，如何在render之前，接收props里的isshow参数，并对他验证，以对其他数据进行处理呢？谢谢！

在install()方法里面，直接使用 this.props.isshow，小程序那边总是提示无法找到属性 isshow。

**Comment by dntzhang** [comment]
小程序自定义组件的勾子不够用！！

**Comment by jzsjiale** [comment]
omi开发小程序，自定义组件的install方法里面，无法处理传递过来的props参数吗？

**Comment by dntzhang** [comment]
试试最新的模板～～

**Comment by dntzhang** [comment]
刚提交了一版本，试试～～  ok的话，我关了这个 issue

**Comment by jzsjiale** [comment]
组件的install方法里面可以调用到props了，但是发现props使用的另一个问题。参考如下场景：

1、有一个自定义组件，是实现弹窗效果，命名为loginpopup，组件有一个data变量是isPopupShow，默认false，在render中使用变量{this.data.isPopupShow}用来控制组件模板是否显示。

2、有一个页面index.tsx，在render中引用上上述的组件
`<loginpopup isshow={this.data.isLoginPopup}></loginpopup>`

3、index.tsx页面中，有一个变量isLoginPopup默认false，使用props方式传递给组件，用来控制组件是否显示。

4、index.tsx页面中，有一个登录按钮，设置了onClick={this.openLoginPopup}方法，用来改变isLoginPopup的值，条件成立时改变为true

5、正常情况下index.tsx中的isLoginPopup改变后，会重新把参数传递给组件loginpopup，在loginpopup组件的beforeRender()中判断，传递过来的props.isshow是否为true，为true的话，改变组件的变量isPopupShow为true，从而实现弹窗页面的展示。


现在的问题是，首次加载index.tsx页面的时候，可以调用loginpopup组件，但是点击登录按钮的时候，执行到组件的beforeRender()时候，会出现死循环，直到报错
`Maximum call stack size exceeded; [Component] Property Observer Error`

组件的isPopupShow值也改变不了

不知道我这样说能明白不？麻烦给看一下，看看是框架的问题，还是我这写法存在问题，谢谢

**Comment by dntzhang** [comment]
```js
data = {
  showIt: false
}

toggle = () => {
  this.data.showIt = !this.data.showIt
  this.update()
}

<todo-footer show={this.data.showIt} ></todo-footer>


beforeRender(){
  this.data.isPopupShow = this.props.show 
}

render() {
  
  let {isPopupShow} = this.data
  return (
    <view class="footer">
      {isPopupShow && <button>toggle me</button>}
    </view>
  )
}
```
刚试了下是可以的，不会出现死循环，这是部分代码

**Comment by dntzhang** [comment]
确定使用了最新的 omip 吗？https://github.com/Tencent/omi/commit/134655b3f933f801bcbae8f87a2aa1a83a165d47

**Comment by jzsjiale** [comment]
是的，我覆盖了define.js，我再试试看

**Comment by jzsjiale** [comment]
我是在组件beforeRender()里对this.data.isPopupShow赋值后，this.update()了一下，就死循环了，去掉this.update()就正常了，这里不能使用this.update()吗？

**Comment by dntzhang** [comment]
不能。而且也不需要～

**Comment by dntzhang** [comment]
所以关下单？？

**Comment by jzsjiale** [comment]
好的，关掉吧，谢谢
