### ISSUE TITLE
请教如何写单元测试？（jest）

### ISSUE THREAD

**Issue by 0o0o00o0o0** [Tencent/omi#286]

**Comment by dntzhang** [comment]
参考这里？https://github.com/Tencent/omi/tree/master/packages/omio/test

**Comment by 0o0o00o0o0** [comment]
您好，请问有测试组件的方法吗？和react类似吗？可以使用enzyme来测试吗？

**Comment by dntzhang** [comment]
enzyme 和 react 绑定，omi 应该用不了

**Comment by sinkcup** [comment]
不能单元测试的框架 意味着 无法验证可靠性，不适合正规项目使用。

**Comment by dntzhang** [comment]
@sinkcup 谁说不能写单元测试？只是不能用 enzyme
