### ISSUE TITLE
omip开发微信小程序，使用vant-weapp的ui框架问题

### ISSUE THREAD

**Issue by jzsjiale** [Tencent/omi#294]
omip开发微信小程序，使用vant-weapp的ui框架，以npm方式安装vant-weapp，在js中如何引入组件比较好呢？

**Comment by dntzhang** [comment]
我明天试试

**Comment by jzsjiale** [comment]
好的，谢谢，直接把vant-weapp的dist目录放到项目文件夹，再一个个引用总感觉很麻烦，还容易出wxs无法找到的问题，以npm方式安装，不知道该如何引入，麻烦给看下，谢谢。

**Comment by dntzhang** [comment]
* https://github.com/Tencent/omi/commit/f922e4e9ec25f74a7ba7db1b11471a6af46f65dc#diff-df2767482ad828ef5c85042dfbfbcb46
* https://nervjs.github.io/taro/docs/mini-third-party.html#%E5%BC%95%E5%85%A5%E7%AC%AC%E4%B8%89%E6%96%B9%E7%BB%84%E4%BB%B6
