### ISSUE TITLE
question: any project like ant design pro?

### ISSUE THREAD

**Issue by cnmade** [Tencent/omi#299]
question: any project like ant desgin pro?
We using ant desgin pro to build our managment system. it base on reactjs. 

tencent omi called next generation FED framework. seems good , so i wonder to know if there project like ant design pro

Ref: https://pro.ant.design/index-cn

**Comment by dntzhang** [comment]
Thank you for your attention.
No at present,We're going to build a set based on omiu in the future.

**Comment by dntzhang** [comment]
Omi Admin

**Comment by cnmade** [comment]
Ok, three years past.
