### ISSUE TITLE
请问是否如taro一致，目前ts项目并不支持sourceMap参看并断点的功能

### ISSUE THREAD

**Issue by acid122** [Tencent/omi#300]
不能查看源码并断点，会严重影响编码体验，这会是选择框架与否的一个重要考量，目前通过微信开发者工具调试，并未找到sourcemap，请问支持吗

**Comment by dntzhang** [comment]
taro有sourceMap吗

**Comment by acid122** [comment]
taro目前好像也不支持，参考:https://github.com/NervJS/taro/issues/671
