### ISSUE TITLE
如何让svg渲染网络图片？

### ISSUE THREAD

**Issue by namewhat** [Tencent/omi#301]
例如我有一段svg，我希望在circle中fill一张图片
<svg width="300" height="220">
    <defs>
        <pattern id="image" x="0" y="0" patternUnits="userSpaceOnUse" height="1" width="1">
            <image x="0" y="0" xlink:href="https://balkangraph.com/js/img/f2.png"></image>
        </pattern>
    </defs>
    <circle id="top" cx="180" cy="120" r="80" fill="url(#image)" />
</svg>

**Comment by namewhat** [comment]
> 例如我有一段svg，我希望在circle中fill一张图片

[](url)

> 例如我有一段svg，我希望在circle中fill一张图片

**Comment by dntzhang** [comment]
cax 的 SVG 还不支持文本和图片，试试 wxml 的 image 盖在上面。或者使用 cax 的 Bitmap，盖在上面

**Comment by namewhat** [comment]
<svg width="300" height="220">
    <defs>
        <pattern id="image" x="0" y="0" patternUnits="userSpaceOnUse" height="1" width="1">
            <image x="0" y="0" xlink:href="https://balkangraph.com/js/img/f2.png"></image>
        </pattern>
    </defs>
    <circle id="top" cx="180" cy="120" r="80" fill="url(#image)" />
</svg>

**Comment by namewhat** [comment]
> cax 的 SVG 还不支持文本和图片，试试 wxml 的 image 盖在上面。或者使用 cax 的 Bitmap，盖在上面

能否提供一下实例？

**Comment by dntzhang** [comment]
https://github.com/dntzhang/cax/blob/master/packages/cax-weapp/index/index.js#L45

**Comment by namewhat** [comment]
> https://github.com/dntzhang/cax/blob/master/packages/cax-weapp/index/index.js#L45

没太看懂，好像没有覆盖的动作。能配合renderSVG实现吗？

**Comment by dntzhang** [comment]
可以

**Comment by namewhat** [comment]
> 可以

我想用svg画类似组织架构那样的图，研究了几天，在小程序里好像不容易实现。可以提供一个例子吗？非常感谢

**Comment by dntzhang** [comment]
> https://github.com/dntzhang/cax/blob/master/packages/cax-weapp/index/index.js#L45

这个例子

**Comment by namewhat** [comment]
> > https://github.com/dntzhang/cax/blob/master/packages/cax-weapp/index/index.js#L45
> 
> 这个例子

下载demo，看了效果我就明白了，可以解决我的问题，谢谢
