### ISSUE TITLE
omi-html

### ISSUE THREAD

**Issue by Wscats** [Tencent/omi#303]
<img width="191" alt="屏幕快照 2019-04-26 下午10 24 01" src="https://user-images.githubusercontent.com/17243165/56814525-f7d47580-6871-11e9-8554-4e173d1f19d8.png">

`omi-html`模块能顺手像`omi`那样打包成`dist`文件夹导出吗，这样比较方便`webpack`中导入，所以希望有空更新下这个模块，谢谢~

```json
{
  "name": "omi-html",
  "version": "0.3.0",
  "description": "Omi Htm integration.",
  "main": "dist/omi-html.js",
  "scripts": {
    "counter": "webpack -w",
    "build": "webpack -w",
    "build-min": "webpack -w"
   // code...
  }
}
```

**Comment by dntzhang** [comment]
最新的omi已经包含，不用再使用 omi-html 了

**Comment by Wscats** [comment]
我留意到omio的组件都是基于局部样式实现的，有没有办法突破shadow dom样式的壁垒，实现全局样式渗透，从而影响局部组件的样式，或者局部组件继承全局的样式呢

**Comment by dntzhang** [comment]
定义一个拥有全局样式的 BaseElement，所有组件继承它。

**Comment by dntzhang** [comment]
还有一种方案，使用 less，所有组件的 less import 全局的

**Comment by Wscats** [comment]
方案一感觉比较合理，如果方案二less，所有组件重复加载同一份样式，在同页面使用所有的组件，那么会有有很多冗余代码吧

**Comment by dntzhang** [comment]
没有的。和方案一同样的效果

**Comment by Wscats** [comment]
后来仔细想想的其实都是一样的，那意思其实不管怎么样，全局样式都是要作为副本进去子组件的<style>标签内部

**Comment by dntzhang** [comment]
是的

**Comment by dntzhang** [comment]
tagname selector 可以自动继承，不用每个组件写，class selector需要写到每个组件里

**Comment by Wscats** [comment]
新版内置的`omi.html`和`omi.htm`方法为何内置在omi源码里面呢，这点有疑惑，是为了方便不写JSX的人，带来额外的将近三四十行的源码，不是好事吧，html在前端编译为JSX这点应该是不必要的性能损耗，在webpack里面完成不是应该最优解吗

**Comment by dntzhang** [comment]
htm 是有轻微运行时开销，但是总有不在乎这点开销得项目和人且不愿配 webpack 且不用 omi-cli 的人。

**Comment by dntzhang** [comment]
而且用 omi.esm.js 可以把  htm tree-shaking 掉的。

**Comment by Wscats** [comment]
是的，本来想提议要生成一份纯净的esm.js，但刚才在最新的omi包看到了
