### ISSUE TITLE
omip 支持props 传值吗？

### ISSUE THREAD

**Issue by gmfenglin** [Tencent/omi#309]
import { WeElement, define } from 'omi'
define('my-first-element', class extends WeElement {
  static defaultProps = {
		name: 'Omi',
		myAge: 18
	}

  render(props) {
    return (
      <h1>Hello, {props.name}! Age {props.myAge}</h1>
    )
  }
})
 import { WeElement, define } from 'omi'
import '../../components/my-first-element'
define('home', class extends WeElement {
    config = {
        usingComponents: {

        }
    }
    onClick = () => {
        console.log('Hello omiu! ');
    }
    render() {
        return (
            <my-first-element name="world"></my-first-element>
        )
    }
});
在小程序里无法获取属性name值。

**Comment by gmfenglin** [comment]
import { WeElement, define } from 'omi'
define('my-first-element', class extends WeElement {
  static defaultProps = {
		name: 'Omi',
		myAge: 18
	}

  render() {
    
    const {name,myAge}=this.props;
    return (
      <h1>Hello, {name}! Age {myAge}</h1>
    )
  }
})
改成这样props可以传值了，但又不支持defaultProps 设置默认值了

**Comment by gmfenglin** [comment]
import { WeElement, define } from 'omi'
define('my-first-element', class extends WeElement {
  static defaultProps = {
    name: 'Omi',
    myAge: 18
  }
  nProps(props) {
    if (!props ||  Object.prototype.toString.call(props) === '[object Array]') return {};
    var result = {};
    Object.keys(props).forEach(function(key) {
      if(props[key]){
        
        result[key] = props[key];
      }
       
    });
    return result;
}
  render() {
     
   
    this.props = Object.assign(
      this.constructor.defaultProps,
      this.nProps(this.props)
    ) 
    const { name, myAge } = this.props;
    return (
      <h1>Hello, {name}! Age {myAge}</h1>
    )
  }
})
完美解決问题。props 可以传值了，又支持defaultProps 设置默认值。

**Comment by dntzhang** [comment]
defaultProps 我今天支持下
