### ISSUE TITLE
使用omi-cli创建的初始项目运行后报错

### ISSUE THREAD

**Issue by XiaoMing6** [Tencent/omi#316]
用omi-cli初始化项目后，运行"npm start"启动项目，发现/src/elements/app/index.js文件报错：
“Module not found: Can't resolve 'omiu/button' in 'F:\test\my-app\src\elements\app'”

将`import "omiu/button"`改为`import "omiu/src/button"`才不会报错。看了一下node_modules里omiu包的内容，没有dist文件夹，感觉是omiu没有编译的问题（使用的omiu的版本号是@0.0.16）

**Comment by dntzhang** [comment]
额～。我修复了。重新安装 omiu～～ 0.0.17。多谢～～
