### ISSUE TITLE
omix支持自定义tabbar组件吗？

### ISSUE THREAD

**Issue by leifeng** [Tencent/omi#340]
`create({})`创建自定义tabar
一直提示我
`Cannot read property 'data' of undefined; [Component] Lifetime Method Error @ custom-tab-bar/index#(anonymous)
TypeError: Cannot read property 'data' of undefined
    at z.store.ready (http://127.0.0.1:24073/appservice/utils/create.js:147:36)
`

**Comment by dntzhang** [comment]
@leifeng 还能复现吗？

**Comment by dntzhang** [comment]
页面没注入 store，使用 Component 构造器定义组件，使用 triggerEvent 和上层通讯
