### ISSUE TITLE
问题：和目前主流的 Vue 或 React 框架相比，有什么优势吗？

### ISSUE THREAD

**Issue by gongph** [Tencent/omi#37]
Q1:  这算重复造轮子吗？

Q2： 和目前主流的 Vue 或 React 框架相比，有什么优势所在吗？

**Comment by dntzhang** [comment]
https://github.com/AlloyTeam/omi/blob/master/tutorial/all.md

看前面一部分的功能特性~~

**Comment by deepkolos** [comment]
@dntzhang 事件处理部可以把press pressing slide clickonce等封装进去~~想问问管线机制是指? 是利用了e.path ?

**Comment by dntzhang** [comment]
管线机制就是绑定在声明式绑定在dom上的古老方式。press pressing slide clickonce这些可以omi-finger不够用吗？ https://github.com/AlloyTeam/omi/tree/master/plugins/omi-finger

**Comment by deepkolos** [comment]
:+1:

**Comment by deepkolos** [comment]
@dntzhang 在demo里面滑动并没有锁住滚动条~ 我想实现一个像微信主页那样的左右滚动的slider , 左右滑动的时候垂直滚动条会被锁住 , 请问这里有没有很好的加锁的方式 ? 目前是使用overflow-y:hidden;但是会直接删除一个本来用于滚动的layer , 当手指释放的时候又重新生成 , 就有那个一丢丢掉帧.

**Comment by rainbowMorelhahahah** [comment]
> https://github.com/AlloyTeam/omi/blob/master/tutorial/all.md
> 
> 看前面一部分的功能特性~~
连接没了

**Comment by dntzhang** [comment]
@rainbowMorelhahahah 
看这个吧，以前的文档没有意义。 https://github.com/Tencent/omi/blob/master/docs/main-concepts.cn.md
