### ISSUE TITLE
omim-text-field

### ISSUE THREAD

**Issue by helibin** [Tencent/omi#374]
报错：
TypeError: Cannot read property 'appendChild' of null
TypeError: Cannot read property 'display' of undefined
![image](https://user-images.githubusercontent.com/14595752/58637610-72872980-8325-11e9-8345-f325fcd67e00.png)

初始化：
omi init-p-ts app
cd app
cnpm i @omim/core

版本：
omi: 3.3.17
npm: 5.6
@omim/core: 0.3.9

代码：
文件 index.tsx
import '@omim/core/text-field'
...
  render() {
    return (
      <m-text-field label='Label' helper-text='helper text' ></m-text-field>
    )
  }
...

**Comment by dntzhang** [comment]
![Jietu20190530-222942](https://user-images.githubusercontent.com/7917954/58639941-9e58de00-832a-11e9-8f24-caae3160eed1.jpg)
![Jietu20190530-223017](https://user-images.githubusercontent.com/7917954/58639946-9f8a0b00-832a-11e9-96a9-c8842ccd2d17.jpg)

我这测试 ok

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/commit/fb71dd3db0689e62b51e33bd523605297b91274f 刚把测试代码提交上去了

**Comment by helibin** [comment]
刚找到问题所在了
  <m-text-field helper-text='Helper Text' label='Label1' ></m-text-field> // ok
  <m-text-field label='Label1' helper-text='Helper Text'  ></m-text-field> // 报错

**Comment by dntzhang** [comment]
没看懂，我两种都试了是ok的

**Comment by dntzhang** [comment]
更新 omi 至 v6.4
