### ISSUE TITLE
使用omix，真机调试直接报一堆错

### ISSUE THREAD

**Issue by onepicse** [Tencent/omi#389]
我直接把omix对应package包导入到小程序然后使用真机调试就出现一堆错误
![image](https://user-images.githubusercontent.com/17473986/59323651-25845980-8d0e-11e9-9e4b-d1132763255c.png)

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/tree/master/packages/omix 直接把这个弄下来啊

**Comment by onepicse** [comment]
@dntzhang 我就是把https://github.com/Tencent/omi.git这个项目直接clone下来然后在package找到omix，复制出来然后导入到微信开发者工具中，真机调试就报错了

**Comment by onepicse** [comment]
找到问题，忘了来关闭，是微信开发者工具的问题，https://developers.weixin.qq.com/community/develop/doc/0008260fa7c9f0b704b8718b151000?highLine=%25E7%259C%259F%25E6%259C%25BA%25E8%25B0%2583%25E8%25AF%2595%25E4%25B8%2580%25E5%25A0%2586%25E9%2594%2599%25E8%25AF%25AF（这是微信社区给出的解释）

**Comment by dntzhang** [comment]
ok
