### ISSUE TITLE
求教如果不使用 Omi.render，如果进行跨组件传值？

### ISSUE THREAD

**Issue by Otto-J** [Tencent/omi#393]
求教一个问题：我现在有一个传统的服务端渲染新闻网站，没有前后端分离。现在想尝试使用 omi 改造一部分页面。

请问在不使用 Omi.render 的情况下，怎么使用状态管理，进行跨组件传值。

![微信截图_20190618151145](https://user-images.githubusercontent.com/9958583/59660816-07ba6700-91dc-11e9-8888-4c1f7554b0f9.png)

**Comment by Otto-J** [comment]
组件之间进行通信。

伪代码如下：

index.html:
```
<body>
    <index-head sign="jz2" name="工程师" >
    </index-head>
    <need-to-close>
        <!-- 一些服务器传入的文本 -->
    </need-to-close>
</body>
```

index-head.jsx:
```
import { WeElement, define } from "omi";
define("index-head", class extends WeElement {
    render(props) {
        closeAd=()=>{
            this.fire('closeAd')
        }
        return (
            <div className="head">
                <button onClick="closeAd"></button>
                <a className="headName" href={"/" + props.sign}>
                    {props.name}
                </a>
            </div>
        );
    }
});

```

**Comment by dntzhang** [comment]
mitt? 或者全局变量，或者 import 一个公共的 json？或者 store 从根节点注入？
https://github.com/developit/mitt
https://tencent.github.io/omi/site/docs/cn.html#/store?index=1&subIndex=6

**Comment by Otto-J** [comment]
理解了。最终我在根节点注入的store。
