### ISSUE TITLE
DateTimePicker插件问题

### ISSUE THREAD

**Issue by Jizhikun** [Tencent/omi#396]
<m-date-time-picker type="date" past="20180101" future="20200101" lan="zh-cn" show={this.timeShow}>
          </m-date-time-picker>
当我用函数改变this.timeShow的值并调用this.update()并没有成功显示组件

**Comment by dntzhang** [comment]
多谢反馈，请使用 omim v0.1.2

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/commit/fdb14f1380bf1e7e14beab243b7ad7d732c9e5d4
