### ISSUE TITLE
cax 在小程序下无法响应touchmove和tap事件

### ISSUE THREAD

**Issue by leanang** [Tencent/omi#403]
对比了小程序cax旧版本的代码，发现wx-hit-render.js中，hitAABB函数缺少了cb参数，导致无法正确回调。
解决：
1.hitAABB(o, evt, cb) 添加cb回调参数
2.添加 cb(target) 回调执行代码

**Comment by dntzhang** [comment]
好。多谢。能 pr 吗？不 pr ，我等晚点看下。
