### ISSUE TITLE
omix store 给对象新增字段，字段没有被监听

### ISSUE THREAD

**Issue by LeachZhou** [Tencent/omi#409]
@dntzhang

**Comment by dntzhang** [comment]
增加字段需要使用 create.obaa.set(xx, xx, xx) 才会被监听

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/tree/master/packages/obaa#other

**Comment by LeachZhou** [comment]
@dntzhang 
```javascript
let obj = {a: 1}
create.obaa.set(obj, 'c', 3)
```
报错 Uncaught (in promise) TypeError: Cannot read property 'watch' of undefined
    at Function.obaa.set (http://127.0.0.1:51284/appservice/common/js/omix/obaa.js:187:18) 
```javascript
    obaa.set = function (obj, prop, value, exec) {
        if (!exec) {
            obj[prop] = value;
        }
        var $observer = obj.$observer;
        $observer.watch(obj, prop);             // 187行
        if (exec) {
            obj[prop] = value;
        }
    };
```

**Comment by LeachZhou** [comment]
![image](https://user-images.githubusercontent.com/18715564/61015910-51076c00-a3c0-11e9-812b-e8b6ee382457.png)

好像只有$observerProps

**Comment by dntzhang** [comment]
提前定义好字段吧，小程序挂载循环依赖的属性会报错。web 没有问题

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/commit/fcfe12d9f72dbf3b35a2fa0f6acfce85c34dfe9a web 的 obaa 更新到 2.0 了

**Comment by LeachZhou** [comment]
> [fcfe12d](https://github.com/Tencent/omi/commit/fcfe12d9f72dbf3b35a2fa0f6acfce85c34dfe9a) web 的 obaa 更新到 2.0 了

2.0用在小程序里可以解决这问题吗？

**Comment by dntzhang** [comment]
@LeachZhou 试了，不能

**Comment by tulongxCodes** [comment]
@dntzhang 
录的视频：https://hjs-app-test.oss-cn-beijing.aliyuncs.com/2019/01/04/demo.mov

**Comment by dntzhang** [comment]
赞！我明天看下

**Comment by dntzhang** [comment]
@tulongxCodes 和你代码一模一样，为啥我这里不能复线。

**Comment by dntzhang** [comment]
![ezgif-3-a15904d51042](https://user-images.githubusercontent.com/7917954/61423233-a05e1700-a941-11e9-95cc-4847a82dad1f.gif)

**Comment by dntzhang** [comment]
看上面的gif

**Comment by tulongxCodes** [comment]
@dntzhang data怎么设定的值？
打开的新页面中？

**Comment by tulongxCodes** [comment]
我的新页面：
js
```
import create from '../utils/create'
create.Page({
    context: { emitter: create.emitter },
    data: {
        text1:'',
        text2: 'wtf',
        json:{
            text3:'',
            text4:'hello world',
        }
    },
    onLoad: function (opt) {
        /** 每个输入框都输入一些值， 然后点击左上角返回首页， 然后再点击进来看！ */
    },
    handleInput1(e) {
        this.oData.text1 = e.detail.value
    },
    handleInput2(e) {
        this.oData.text2 = e.detail.value
    },
    handleInput3(e) {
        this.oData.json.text3 = e.detail.value
    },
    handleInput4(e) {
        this.oData.json.text4 = e.detail.value
    }
})
```
wxml:
```
<!--pages/test.wxml-->
<text>pages/test.wxml</text>

text1:
<input bindinput="handleInput1" value="{{text1}}"></input>
text2:
<input bindinput="handleInput2" value="{{text2}}"></input>
text3:
<input bindinput="handleInput3" value="{{json.text3}}"></input>
text4:
<input bindinput="handleInput4" value="{{json.text4}}"></input>
```

**Comment by dntzhang** [comment]
和你的代码一模一样。奔溃了～～    求复现路径！！！！！

**Comment by tulongxCodes** [comment]
@dntzhang 
demo：
https://hjs-app-test.oss-cn-beijing.aliyuncs.com/2019/01/04/miniprogram-1.zip

**Comment by tulongxCodes** [comment]
em。。会不会和基础库有关。我的是2.7.3 ，2.7.5也有问题，没有一个一个的测

**Comment by dntzhang** [comment]
晕死。居然跟 test.json 的 usingComponents 有关。去掉就好了，感觉这个锅 omix 不背。

**Comment by tulongxCodes** [comment]
@dntzhang ???
这个有问题啊，虽然配置了这个usingComponents，但是里面没有任何组件；而且这个是开发工具默认创建的，里面就包含这个字段。
可以做判定，如果没有任何属性内容，不生效嘛？

**Comment by dntzhang** [comment]
这个omix不可控

**Comment by h-dongyu** [comment]
这个问题是否是因为omix demo里的obba是1.0.0
https://github.com/Tencent/omi/blob/master/packages/omix/utils/obaa.js,
第9行 //if (!target.$observer) target.$observer = this 被注释掉引起的？

```
//复现代码
obj = {x: 1, y: 2};
obaa(obj, function(){ console.log('test'); });
obaa.set(obj, 'z', 3);       //obba.js 第9行注释时会报错，打开后正常
obj.z = 4;
```

**Comment by dntzhang** [comment]
omix 2.0 支持新增响应式属性

this.store.set(this.store.data, 'newProp', 'newPropVal')  //会触发视图更新
this.store.data.newProp = 'newPropVal' //新增属性不会触发视图更新，必须使用 create.set

**Comment by liuyihua-cn** [comment]
> omix 2.0 支持新增响应式属性
> 
> ```js
> this.store.set(this.store.data, 'newProp', 'newPropVal')  //会触发视图更新
> this.store.data.newProp = 'newPropVal' //新增属性不会触发视图更新，必须使用 create.set
> ```

您好，测试发现并不能够使用该特性，是否是因为obba.js仍然为1.0的原因？
