### ISSUE TITLE
注意：开发者关于项目后续开发的维护问题

### ISSUE THREAD

**Issue by goldiwill** [Tencent/omi#41]
- 问题1：随着后续开发的进行项目会变得复杂多变，后期能否平滑的过渡升级
- 问题2：打包编译后，是否还需要加载编译部分的模块，如art-template 等等
- 问题3：组件的更新能否提供默认的更新策略，并提供策略的更新配置是否开启或关闭默认的更新
- 问题4：路由是否支持嵌套使用，使用参数的和路由检测的策略会有哪些变化
- 问题5：目前能否实现模块的延迟加载
- 问题6：是否有打算实现ssr这部分功能

**Comment by dntzhang** [comment]
1. 后期会向下兼容平滑过渡，其实前期各个版本也是比较平滑
2. 使用 omi.art.js 不需要使用 art-template
3.  更新必须调用 update 或者 updateSelf。 可以通过声明 preventSelfUpdate 阻止组件内部自己的update
4. router还是单例比较好， OmiRouter.init只能执行一次，router规则全部集中在一个地方。如果有渲染到其他节点的需求，可以在每个route里加对应的renderTo。比如:
```js
OmiRouter.init({
    routes: [
        {path: '/', component: Home},
        {path: '/about', component: About},
        {path: '/user-list', component: UserList},
        {path: '/user/:name/category/:category', component: User, renderTo: "#otherView"}
    ],
    renderTo: "#view",
    defaultRoute: '/',
    root: this
})
```
5.参见 omi-cli 的代码分割部分，使用 [https://github.com/AlloyTeam/omi-cli#代码分割](https://github.com/AlloyTeam/omi-cli#代码分割)
6.目前没有打算

**Comment by RubyLouvre** [comment]
欢迎加入 370262116，一起讨论迷你React，本群已经收集了三个迷你React的作者了

**Comment by dntzhang** [comment]
@RubyLouvre 赞，已申请~
