### ISSUE TITLE
omix中心化时，自定义的组件里如何获取、修改全局store的状态并更新？

### ISSUE THREAD

**Issue by dongweb** [Tencent/omi#414]
omix中心化时，自定义的组件里如何获取、修改全局store的状态并更新？

**Comment by dntzhang** [comment]
this.store.data 全局 store 和 data，页面和页面所有组件可以拿到， 操作 data 会自动更新视图

**Comment by dongweb** [comment]
@dntzhang 你好，可能没描述太清楚，我的意思是，当使用中心化api时，在子组件模板里确实能通过{{store.xxx}}获取到全局状态，但是在子组件js里貌似没有办法修改全局store的状态呢？

**Comment by dntzhang** [comment]
this.store.data = 'xx'
this.store.data.xx = xxx

直接改啊

**Comment by dongweb** [comment]
刚使用，多谢多谢。
