### ISSUE TITLE
关于o-repeat写法改进

### ISSUE THREAD

**Issue by jiayisheji** [Tencent/omi#42]
现在ng2和ng4，vue2都换成for-of写法了。
可以统一一下，切换成本。
建议改成o-for="item of items"这样的写法。

**Comment by dntzhang** [comment]
@dorsywang

**Comment by dorsywang** [comment]
@jiayisheji 好的，我们增加一下for指令， 可以关注下sodajs的项目

**Comment by jiayisheji** [comment]
@dntzhang 嗯好的。
