### ISSUE TITLE
react-kbone支持hooks了吗

### ISSUE THREAD

**Issue by chenjigeng** [Tencent/omi#420]
刚才试了下，目前支持的preact版本是8.X，不支持hooks。我手动升级到10.X后，试用了下hooks，发下state更新了，不过页面绑定值没有更新。

**Comment by dntzhang** [comment]
10  还没正式发布，等发了正式版再试。

**Comment by dntzhang** [comment]
已经支持 hook。https://github.com/Tencent/omi/tree/master/packages/react-kbone
