### ISSUE TITLE
omix的中心化store在app.js中怎么使用

### ISSUE THREAD

**Issue by scutcl** [Tencent/omi#427]
@dntzhang

**Comment by dntzhang** [comment]
import store进去用

**Comment by scutcl** [comment]
import store改变store.data，有时候界面不会刷新

**Comment by cgygd** [comment]
> import store改变store.data，有时候界面不会刷新

请问在什么情况下界面不会刷新？目前有项目准备用这个，用来更新用户授权信息。不知道有没有问题。你的场景是怎样的？

**Comment by frei-x** [comment]
用到store的页面,记得use
