### ISSUE TITLE
Created a mini library using Omi

### ISSUE THREAD

**Issue by kethan** [Tencent/omi#428]
Hi,
I created a library using omi similar to hyperapp for functional programming.
Please let me know your feedback.

https://codesandbox.io/s/omi-ts-bhq64

Thanks for awesome Omi.

**Comment by dntzhang** [comment]
Very cool！

**Comment by dntzhang** [comment]
https://codepen.io/omijs/pen/abowpZW

I added functional style define method to omi in v6.10.0.

```jsx
import { define, render } from 'omi'

class Store {
  data = {
    count: 1
  }
  sub = () => {
    this.data.count--
  }
  add = () => {
    this.data.count++
  }
}

define('my-counter', ['count'], _ => (
  <div>
    <button onClick={_.store.sub}>-</button>
    <span>{_.store.data.count}</span>
    <button onClick={_.store.add}>+</button>
  </div>
))

render(<my-counter />, 'body', new Store)
```

**Comment by Wscats** [comment]
@kethan I transform the core files - `app.ts`, so that you can achieve in-depth object observe or proxy.

```js
import { define, WeElement, html, h, extend, get, set } from "omi";

export interface appOptions {
    name: string;
    view(props?: any, state?: any, ref?: any);
    state?: any;
    propTypes?: any;
    props?: any;
    defaultProps?: any;
    css?: string;
    install?(props?: any, state?: any, ref?: any);
    installed?(props?: any, state?: any, ref?: any);
    uninstall?(props?: any, state?: any, ref?: any);
    beforeUpdate?(props?: any, state?: any, ref?: any);
    updated?(props?: any, state?: any, ref?: any);
    beforeRender?(props?: any, state?: any, ref?: any);
    receiveProps?(props?: any, state?: any, ref?: any);
}

// Added code
const isObject = obj => Object.prototype.toString.call(obj) === '[object Object]';
// Added code
const observify = (obj, that) => {
    if (!isObject(obj)) {
        return obj;
    }
    Object.keys(obj).forEach(key => {
        obj[key] = observify(obj[key], that);
    });

    return Observer(obj, that);
}
// Added code
const Observer = (obj, that) => {
    return new Proxy(obj, {
        set(obj, prop, value) {
            const res = Reflect.set(obj, prop, value);
            that.update();
            return res;
        }
    });
}

const app = ({
    name,
    view,
    state,
    propTypes,
    props,
    defaultProps,
    css,
    install,
    installed,
    uninstall,
    beforeUpdate,
    updated,
    beforeRender,
    receiveProps
}: appOptions) => {
    define(name, class extends WeElement {
        state = Object.assign({}, state);

        static props = props;
        static propTypes = propTypes;
        static defaultProps = defaultProps;
        static css = css;
        private ref;

        constructor() {
            super();
            (that => {
                // Added code
                that.state = observify(that.state, that)
            })(this);
        }

        install() {
            install &&
                install(
                    this.props ? this.props : {},
                    this.state ? this.state : {},
                    this
                );
        }

        installed() {
            installed &&
                installed(
                    this.props ? this.props : {},
                    this.state ? this.state : {},
                    this
                );
        }

        uninstall() {
            uninstall &&
                uninstall(
                    this.props ? this.props : {},
                    this.state ? this.state : {},
                    this
                );
        }

        render(oProps, oState) {
            return view(
                this.props ? this.props : oProps,
                this.state ? this.state : oState,
                this
            );
        }
    });
};

extend("model", (el: any, path, scope) => {
    el.value = get(scope, path);
    el.addEventListener("input", () => {
        set(scope, path, el.value);
        scope.update();
    });
});

export { html, h, app };
```

**Comment by kethan** [comment]
> Very cool！You may need [obaa](https://github.com/Tencent/omi/tree/master/packages/obaa) or [JSONPatcherProxy](https://github.com/Palindrom/JSONPatcherProxy) observe or proxy any object's any change, such as:
> 
> ```js
> this.state.a.b.c = 1
> this.state.e.f.arr.push('aa')
> this.state.g.h[2] = { c: 1 }
> this.state.g.h[2].c = 3
> ```

Yes you are right.

**Comment by kethan** [comment]
> https://codepen.io/omijs/pen/abowpZW
> 
> I added functional style define method to omi in v6.10.1.
> 
> ```js-jsx
> import { define, render } from 'omi'
> 
> class Store {
>   data = {
>     count: 1
>   }
>   sub = () => {
>     this.data.count--
>   }
>   add = () => {
>     this.data.count++
>   }
> }
> 
> define('my-counter', ['count'], _ => (
>   <div>
>     <button onClick={_.store.sub}>-</button>
>     <span>{_.store.data.count}</span>
>     <button onClick={_.store.add}>+</button>
>   </div>
> ), {
>     css: `span { color: red; }`,
>     installed() {
>       console.log('installed')
>     }
>   })
> 
> render(<my-counter />, 'body', new Store)
> ```

Looks good. But what about props, defaultprops, etc. I never understand what is ['count'] is used for.

**Comment by kethan** [comment]
> @kethan I transform the core files - `app.ts`, so that you can achieve in-depth object observe or proxy.
> 
> ```js
> import { define, WeElement, html, h, extend, get, set } from "omi";
> 
> export interface appOptions {
>     name: string;
>     view(props?: any, state?: any, ref?: any);
>     state?: any;
>     propTypes?: any;
>     props?: any;
>     defaultProps?: any;
>     css?: string;
>     install?(props?: any, state?: any, ref?: any);
>     installed?(props?: any, state?: any, ref?: any);
>     uninstall?(props?: any, state?: any, ref?: any);
>     beforeUpdate?(props?: any, state?: any, ref?: any);
>     updated?(props?: any, state?: any, ref?: any);
>     beforeRender?(props?: any, state?: any, ref?: any);
>     receiveProps?(props?: any, state?: any, ref?: any);
> }
> 
> // Added code
> const isObject = obj => Object.prototype.toString.call(obj) === '[object Object]';
> // Added code
> const observify = (obj, that) => {
>     if (!isObject(obj)) {
>         return obj;
>     }
>     Object.keys(obj).forEach(key => {
>         obj[key] = observify(obj[key], that);
>     });
> 
>     return Observer(obj, that);
> }
> // Added code
> const Observer = (obj, that) => {
>     return new Proxy(obj, {
>         set(obj, prop, value) {
>             const res = Reflect.set(obj, prop, value);
>             that.update();
>             return res;
>         }
>     });
> }
> 
> const app = ({
>     name,
>     view,
>     state,
>     propTypes,
>     props,
>     defaultProps,
>     css,
>     install,
>     installed,
>     uninstall,
>     beforeUpdate,
>     updated,
>     beforeRender,
>     receiveProps
> }: appOptions) => {
>     define(name, class extends WeElement {
>         state = Object.assign({}, state);
> 
>         static props = props;
>         static propTypes = propTypes;
>         static defaultProps = defaultProps;
>         static css = css;
>         private ref;
> 
>         constructor() {
>             super();
>             (that => {
>                 // Added code
>                 that.state = observify(that.state, that)
>             })(this);
>         }
> 
>         install() {
>             install &&
>                 install(
>                     this.props ? this.props : {},
>                     this.state ? this.state : {},
>                     this
>                 );
>         }
> 
>         installed() {
>             installed &&
>                 installed(
>                     this.props ? this.props : {},
>                     this.state ? this.state : {},
>                     this
>                 );
>         }
> 
>         uninstall() {
>             uninstall &&
>                 uninstall(
>                     this.props ? this.props : {},
>                     this.state ? this.state : {},
>                     this
>                 );
>         }
> 
>         render(oProps, oState) {
>             return view(
>                 this.props ? this.props : oProps,
>                 this.state ? this.state : oState,
>                 this
>             );
>         }
>     });
> };
> 
> extend("model", (el: any, path, scope) => {
>     el.value = get(scope, path);
>     el.addEventListener("input", () => {
>         set(scope, path, el.value);
>         scope.update();
>     });
> });
> 
> export { html, h, app };
> ```

This looks perfect. I will implement this. Thanks.

**Comment by kethan** [comment]
> Very cool！You may need [obaa](https://github.com/Tencent/omi/tree/master/packages/obaa) or [JSONPatcherProxy](https://github.com/Palindrom/JSONPatcherProxy) observe or proxy any object's any change, such as:
> 
> ```js
> this.state.a.b.c = 1
> this.state.e.f.arr.push('aa')
> this.state.g.h[2] = { c: 1 }
> this.state.g.h[2].c = 3
> ```

is there any way I can import JSONPatchProxy from omi?

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/releases/tag/v6.11.0

**Comment by dntzhang** [comment]
import { render, define } from '../../src/omi'

class Store {
  data = {
    count: 1
  }
  sub = () => {
    this.data.count--
  }
  add = () => {
    this.data.count++
  }
}

define('my-counter', ['count'], _ => {
//_.props
//_.constructor.propTypes
//_.constructor.defaultProps
 return <div>
    <button onClick={_.store.sub}>-</button>
    <span>{_.store.data.count}</span>
    <button onClick={_.store.add}>+</button>
  </div>
}, {
    propTypes: { }, //can define here
    defaultProps: { }, //can define here
    css: `span { color: red; }`,
    installed() {
      console.log('installed')
    }
  })

**Comment by dntzhang** [comment]
```
define('my-counter', ['count', 'a[1]', 'b.c.e'], _ => {
```
The second parameter represents proxy path, more  infohttps://tencent.github.io/omi/site/docs/index.html#/store?index=1&subIndex=8

**Comment by kethan** [comment]
Thank you. All done. Need to fix type error on JSONProxy.

**Comment by kethan** [comment]
![image](https://user-images.githubusercontent.com/19235/64190208-d1d46880-ce43-11e9-9798-2f0e4d4b2ad8.png)

**Comment by dntzhang** [comment]
> Thank you. All done. Need to fix type error on JSONProxy.

Fixed.

**Comment by kethan** [comment]
Tried the same code in omio. Below are not working 

1. render(props,state) not working.
2. 2-way binding not found

**Comment by dntzhang** [comment]
1.render(props,state) not working.

what's `render(props,state) `? show me more detail info

2. 2-way binding not found

It's in the todo list!
