### ISSUE TITLE
omix store在tabbar中修改数据没有更新

### ISSUE THREAD

**Issue by scutcl** [Tencent/omi#432]
在tabbar中修改store，其它tabbar页面没有监听到数据变化

**Comment by stys35** [comment]
https://jsfiddle.net/

**Comment by daiyifei** [comment]
遇到了同样的问题

**Comment by dntzhang** [comment]
omix 2.0也有这问题吗？

**Comment by dntzhang** [comment]
发一个能复现的链接例子来看下

**Comment by dntzhang** [comment]
验证是 ok 的，不复现。 https://developers.weixin.qq.com/s/EvePqKmT7Nce

**Comment by daiyifei** [comment]
> omix 2.0也有这问题吗？ @daiyifei

https://developers.weixin.qq.com/s/JMwBUKm97qcH
跳转到Page2的时候触发了更新但页面没有变化，跳回Page1的时候页面刷新了两次

**Comment by dntzhang** [comment]
https://developers.weixin.qq.com/s/WeLyCKmd7Dcj 这个问题在 2.3.3 已经修复了。 @daiyifei

**Comment by daiyifei** [comment]
> https://developers.weixin.qq.com/s/WeLyCKmd7Dcj 这个问题在 2.3.3 已经修复了。 @daiyifei

非常感谢
