### ISSUE TITLE
omix中心化时, 可否最后使用 Component 构造器构造页面;

### ISSUE THREAD

**Issue by haloFi** [Tencent/omi#435]
![image](https://user-images.githubusercontent.com/21139434/65132358-6c7f9a80-da33-11e9-8fb1-37c290ae70f1.png)

https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/component.html

这样在使用中心化创建页面的时候, 可以使用 behaviors 来提取所有页面中公用的代码段

**Comment by dntzhang** [comment]
求 pr

**Comment by dntzhang** [comment]
纯组件不用不用 create 创建，直接使用 Component，且该组件内使用 triggerEvent 通知父组件改变 store.data 或者调用 store 的方法与外界通讯。

**Comment by dntzhang** [comment]
可以

**Comment by fanlei1988** [comment]
我也遇到了这个问题，想知道目前有解决方案么？
我看create.js 构建源码的时候，取的是当前页，但是如果跳转的页面是通过Component构造器创建的话，是取不到page.store.data 的，所以会报错
还在纠结当中。。。求解惑

**Comment by dntzhang** [comment]
用的omix 1.0还是 2.0 @fanlei1988

**Comment by dntzhang** [comment]
2.0是可以的

**Comment by fanlei1988** [comment]
用的2.0 
场景 ： 页面A   组件B ， 页面C（使用Component构造器构建的）
关系： 页面A包含组件B ，组件B 跳转到页面C ，页面C操作完回到页面A

页面A使用create和store 构建  
组件B使用create构建
页面C使用crate构建

当跳转到C页面初始化的是时候取到的page.store 是未定义的
```
  const page = getCurrentPages()[getCurrentPages().length - 1]
      store.use && (this.__updatePath = getPath(store.use))
      this.store = page.store
      this.__use = store.use
      this.computed = store.computed
      store.data = this.store.data
```
因为page  对象是当前页，也就是页面C，所以取不到store.data

**Comment by fanlei1988** [comment]
这是在create.js 源码第82行，最新版2.3.5 

因为对小程序不是很熟练，所以查了一下getCurrentPages()的用法，如果这个地方我改成遍历page对象，取store.data 存在的page对象，是可以完成初始化的。但是我不知道这样做，对整体会有什么影响？
```
	  //测试代码
	  const page = getCurrentPages().filter(function(item,index){
		  return item.store && item.store.data
	  })[0];
```
@dntzhang

**Comment by dntzhang** [comment]
会有影响，因为可以有多页面多 store 的情况。

**Comment by dntzhang** [comment]
可能api要稍微调整了。component也可以跟page一样注入 store

**Comment by fanlei1988** [comment]
@dntzhang 嗯嗯，感谢您的解答，期待您的调整！

如果将getCurrentPages() 倒序排列，取第一个匹配的，感觉还是能暂时满足需求，还是更期待您的答案

谢谢。

**Comment by dntzhang** [comment]
omix 2.4 已经支持

**Comment by dntzhang** [comment]
create.Page(store, option) 创建页面， store 从页面注入，可跨页面跨组件共享, 如果 option 定义了 data，store 的 data 会挂载在 this.data.$ 下面
create.Component(option) 创建组件
create.Component(store, option) 创建组件页面
