### ISSUE TITLE
omim Tree控件点击没有反应

### ISSUE THREAD

**Issue by Jizhikun** [Tencent/omi#456]
![C597BADF-8629-4ebc-B7D8-8B38103BE3AC](https://user-images.githubusercontent.com/16830977/66557264-29bd6800-eb84-11e9-8097-bfd71e0792f2.png)

**Comment by dntzhang** [comment]
无法折叠吗？需要什么反应

**Comment by Jizhikun** [comment]
> 无法折叠吗？需要什么反应

是的，无法进行折叠操作

**Comment by dntzhang** [comment]
我这边试了是可以了，要点item左边的箭头进行折叠和展开

**Comment by Jizhikun** [comment]
> 我这边试了是可以了，要点item左边的箭头进行折叠和展开

`	toggleHandler = (evt) => {
		console.log(evt.detail.id)
	}

	onNodeClick = (evt) => {
		console.log(evt.detail)
	}

	onCheck = (evt) => {
		console.log(evt.detail)
	}

	render() {
		return <div>
			<m-tree
				checkbox
				onNodeClick={this.onNodeClick}
				onToggle={this.toggleHandler}
				onCheck={this.onCheck}
				node={this.node}>
			</m-tree>
		</div>

	}`
这个就是你例子中的代码，调试的时候点击也触发了这三个函数，但并没有产生折叠、选中、取消这些动作

**Comment by dntzhang** [comment]
https://tencent.github.io/omi/packages/omim/docs/build/index.html#/tree?index=7&subIndex=7

**Comment by dntzhang** [comment]
你看这个例子是可以的啊

**Comment by Jizhikun** [comment]
> https://tencent.github.io/omi/packages/omim/docs/build/index.html#/tree?index=7&subIndex=7

好的，谢谢，我们排查一下框架是不是搭的有问题
