### ISSUE TITLE
omim Tree控件收缩一次后报错

### ISSUE THREAD

**Issue by GithubTeemo** [Tencent/omi#457]
你好，我按照github上面的demo展示tree控件到界面上面，但是第一次收缩或者点击后控制台报错，无法再次进行点击。
报错内容如下：
![TIM截图20191011092118](https://user-images.githubusercontent.com/18589811/66617656-98440980-ec08-11e9-9d82-1a1f9eb36800.png)
调试结果如下：
![TIM截图20191011092139](https://user-images.githubusercontent.com/18589811/66617677-b578d800-ec08-11e9-99a3-ad91e5046503.png)

**Comment by dntzhang** [comment]
收到，我一会儿看下。

**Comment by dntzhang** [comment]
你把 package.json 的 alias 去掉。omim 不支持 omio

**Comment by GithubTeemo** [comment]
好的，谢谢
