### ISSUE TITLE
使用omim的组件时出现property 'querySelector' of undefined错误

### ISSUE THREAD

**Issue by clll7** [Tencent/omi#458]
### 问题：
使用omim的l组件时出现如下错误，无法正常使用。
![微信截图_20191011103652](https://user-images.githubusercontent.com/6949822/66620473-2c1ad300-ec13-11e9-9193-4f1ec92e4988.png)

### 代码：
```js
import 'omim/button'
import { define, WeElement, render, h } from 'omi'

define('my-app', class extends WeElement {
  render() {
    return <div>
      <m-button>Default</m-button>
    </div>
  }
})
render(<my-app />, 'body')
```

### omi版本：
6.15.1

**Comment by dntzhang** [comment]
把 package.json 里的  alias 去掉，不然使用了 omio。omim 只能使用 omi，不能使用 omio

**Comment by clll7** [comment]
可以了，thanks
