### ISSUE TITLE
omim  expansion组件报“querySelector”错误

### ISSUE THREAD

**Issue by tu3susu** [Tencent/omi#465]
使用omi-route跳转时，目标页expansion组件报错，刷新目标页，组件又能正常使用。报错信息如下：
![3D{5K`D`3@PGUMRJUBHYVDP](https://user-images.githubusercontent.com/42396647/66990052-0f413c80-f0f8-11e9-85ac-3034e4cb47e8.png)

**Comment by tu3susu** [comment]
> 去掉 package.json 里的 alias。不然会使用 omio 渲染。omio 不支持 omim

现在搭的框架是单页面应用，package.json中没有alias

**Comment by dntzhang** [comment]
多谢。修复了。更新至 omim 0.2.1
