### ISSUE TITLE
omi-router出错

### ISSUE THREAD

**Issue by tu3susu** [Tencent/omi#469]
使用omi init spa新建单页应用，运行时出错，出错如下：
![28RUF`D}4AV%%}@ 29L WGX](https://user-images.githubusercontent.com/42396647/67082298-74199700-f1cb-11e9-89ff-3363e75a7503.png)
此错误升级omi版本前未出现，升级后报错，版本号
omi：6.15.6
omi-route:2.0.11

**Comment by dntzhang** [comment]
正在看

**Comment by dntzhang** [comment]
这个模板已经废弃。建议使用标签模板，然后自行导入 router。https://github.com/Tencent/omi/blob/master/packages/omi-router/README.CN.md
