### ISSUE TITLE
omi-router出错

### ISSUE THREAD

**Issue by tu3susu** [Tencent/omi#470]
新建标准模板，导入omi-router，报错。
代码如下
![(J{YMY26@8)RY FCZ95 @YJ](https://user-images.githubusercontent.com/42396647/67447808-b0277e80-f647-11e9-8352-459bbb0af081.png)
在install route后，data并未获取值，导致data.tag报错
![1Y@ 8 {8H$U4R%P~}@4~K`P](https://user-images.githubusercontent.com/42396647/67447908-f54bb080-f647-11e9-91ff-227b4adc6ffe.png)

**Comment by dntzhang** [comment]
render 第二个参数不是 data。请在 render 使用 this.data

**Comment by tu3susu** [comment]
this.data 没有tag参数

**Comment by dntzhang** [comment]
data = { tag: "my-home"}  

你代码里不是定义了吗
