### ISSUE TITLE
omix js 页面数据不在渲染

### ISSUE THREAD

**Issue by YanSha0407** [Tencent/omi#471]
在index.js 中的data 定义一个title 然后在index.wxml 中的{{title}}不显示

**Comment by YanSha0407** [comment]
1

**Comment by dntzhang** [comment]
为啥关了？额。omix v2 不允许定义私有 data

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/issues/474 已经支持私有 data @YanSha0407
