### ISSUE TITLE
关于 omix 不支持定义私有 data 的疑惑

### ISSUE THREAD

**Issue by Leskur** [Tencent/omi#474]
项目一开始的时候没有使用 omix 做状态管理，后来由于业务需求引用了 omix，但是使用过程中发现 [omix v2 不允许定义私有 data](https://github.com/Tencent/omi/issues/471#issuecomment-547833296)。

如果不支持定义私有 data 的话，那么在项目上使用 omix 的时候，是否就需要把所有页面原有的 data 都合并到 store  中？

在页面数量过多的时候，我想这是一件比较痛苦的事。

对比了一下 [omix](https://github.com/Tencent/omi/tree/master/packages/omix)、[omix-v1](https://github.com/Tencent/omi/tree/master/packages/omix-v1)、[westore](https://github.com/Tencent/westore)、[dd-store](https://github.com/linjc/dd-store)，发现后三者都支持定义私有 data。

想请教一下，是什么原因，导致 omix 舍弃了 omix-v1 支持定义私有 data 的特性呢？

这是否违背了 omix 对小程序零入侵的特性？

**Comment by dntzhang** [comment]
今天给你一个满意的答案。

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/commit/157ffe5a417a5f6c6acd954f3c5886e65a33ee43

**Comment by dntzhang** [comment]
### 答：支持页面拥有私有 data:

举个例子：

```js
create(store, {
  use: [
    'motto',
    'userInfo',
    'hasUserInfo',
    'canIUse'
  ],
  computed: {
    reverseMotto() {
      return this.motto.split('').reverse().join('')
    }
  },
  data: {
    name: 'omix'
  },
```

这个时候全局 store 的 data 会挂在在 `data.$` 下，所以绑定 wxml 的时候需要加上前缀，比如:

```html
<!--index.wxml-->
<view class="container">
  <view class="userinfo">
    <button wx:if="{{!$.hasUserInfo && $.canIUse}}" open-type="getUserInfo" bindgetuserinfo="getUserInfo"> 获取头像昵称 </button>
    <block wx:else>
      <image bindtap="bindViewTap" class="userinfo-avatar" src="{{$.userInfo.avatarUrl}}" mode="cover"></image>
      <text class="userinfo-nickname">{{$.userInfo.nickName}}</text>
    </block>
  </view>
  <view class="usermotto">
    <text class="user-motto">{{$.motto}}-{{reverseMotto}}-{{name}}</text>
  </view>
  <test-store />
</view>
```

注意，data 和 computed 的属性不需要 $ 前缀。

**Comment by Leskur** [comment]
好的，感谢解答~
