### ISSUE TITLE
omix 页面只有引入store的值,就setData store中所有值,这样会影响页面渲染吗

### ISSUE THREAD

**Issue by weijia520** [Tencent/omi#475]

**Comment by dntzhang** [comment]
描述得有点抽象，举个具体例子？还有就是试试就可以知道结果。

**Comment by dntzhang** [comment]
用了store基本上用不上 setData 啊

**Comment by weijia520** [comment]
AppData中的数据不是可以显示页面data中的数据嘛,只要用了store,store的所有值都会在$下面,像这种会影响页面渲染嘛,毕竟一般store的数据量比较大的

**Comment by dntzhang** [comment]
太抽象了，写点代码出来我看下你到底遇到什么问题。

**Comment by weijia520** [comment]
假设 store定义了 a,b,c 

页面js 只使用a

create(store, {
  use: [
    'a'
  ]

b,c俩个值也有
 this.store.data.b
 this.store.data.c
...

页面wxml中获取数据  {{$.}} a,b,c 也都有值

这不是按需使用的吗
现在是一旦使用了  就相当于引入了所有值

**Comment by dntzhang** [comment]
第一次渲染所有值都可以使用到的。这个没有关系。use 的声明只要更新的时候起作用，根据 use 的声明进行按需更新，

**Comment by weijia520** [comment]
好像是每个页面只要使用了，所有值都会有，数据量不会有影响吗？use声明不应该是按需加载吗？

**Comment by dntzhang** [comment]
不会

**Comment by weijia520** [comment]
恩，好的，感谢解惑
