### ISSUE TITLE
omix定义私有data中的引用类型值在页面卸载后没有销毁，在页面重新加载后未重置？

### ISSUE THREAD

**Issue by fyuan1992** [Tencent/omi#477]
问题：
a页面进入b页面，b页面中有私有data
在b页面中更改私有data中引用类型的值后，b页面销毁后，其私有data中引用类型的值不销毁，在b页面重新载入时，私有data中引用类型的数据不重置

看不太懂omix，要不然就pr了:sob:，所以提交issues，问问大佬们

复现：100%复现

附上代码片段：https://developers.weixin.qq.com/s/kIAm2Hmo7fcE

**Comment by fyuan1992** [comment]
目前是在进入页面时将私有data手动重置一下:stuck_out_tongue_closed_eyes:

**Comment by dntzhang** [comment]
明明是 feature，被说是 bug 😁

**Comment by fyuan1992** [comment]
> 明明是 feature，被说是 bug

大佬说是feature就是feature，:joy:，指点一下怎么把这个feature优化一下呗:yum:

**Comment by dntzhang** [comment]
不用 omix 的原生小程序能重置引用类型吗？

**Comment by dntzhang** [comment]
我优化下

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/commit/e2bdeaba305a88e01592e7a699e0ec2ac5cc873a

**Comment by fyuan1992** [comment]
> [e2bdeab](https://github.com/Tencent/omi/commit/e2bdeaba305a88e01592e7a699e0ec2ac5cc873a)

好快:thumbsup:
