### ISSUE TITLE
小程序里使用omix的疑问，关于组件不更新的问题

### ISSUE THREAD

**Issue by fanlei1988** [Tencent/omi#481]
场景：
（1）1个Page页面，假如变量是 a
（2）1个组件，使用变量a
（3）同时page页面含有私有变量 

当加载的时候，a在Page和组件里都有值显示，当更改a的时候，Page页面更改，组件里不更改

通过调试，找到一处地方，create.js  的130行 如下：
```
for (let pk in kv) {
     if (!/\$\./.test(pk)) {
            kv['$.' + pk] = kv[pk]
            delete kv[pk]
      }
 }
```
在create.js 里的_update 方法里，赋值的时候同时删除了这个属性，导致在更新组件的时候，needUpdate(kv, ins.__updatePath) 方法是false 没有走组件的更新

我不知道删除原属性的初衷是什么，还是这个一个小bug？请解惑

**Comment by dntzhang** [comment]
确实没有必要删

**Comment by dntzhang** [comment]
修复了。非常感谢 
 https://github.com/Tencent/omi/commit/191953f6ee14e571d00374f9e9864d70b9515f50
