### ISSUE TITLE
omix 2.0  多次跳转到同一个页面中，只有最后一个页面可以响应式地修改全局状态，返回前面的页面是看不到修改后的数据，也无法响应式地修改！？？

### ISSUE THREAD

**Issue by banduoju** [Tencent/omi#486]

**Comment by dntzhang** [comment]
分享一个代码链接出来。或者贴一些代码。你说的是 omix？ omix哪个版本？

**Comment by banduoju** [comment]
> 分享一个代码链接出来。或者贴一些代码。你说的是 omix？ omix哪个版本？
js：
     import create from '../../utils/create'
import store from '../../store/index'

create(store, {
  use: [
    'motto'
  ],
  computed: {

  },
  data: {
    name: 'omix'
  },
  onLoad: function () {

  },
  goCurrent () {
    wx.navigateTo({
      url:'/pages/index-with-data/index'
    })
  },
  change () {
    this.store.data.motto = this.store.data.motto + 'x1'
  },
})

wxml:
    
   import create from '../../utils/create'
import store from '../../store/index'

create(store, {
  use: [
    'motto'
  ],
  computed: {

  },
  data: {
    name: 'omix'
  },
  onLoad: function () {

  },
  goCurrent () {
    wx.navigateTo({
      url:'/pages/index-with-data/index'
    })
  },
  change () {
    this.store.data.motto = this.store.data.motto + 'x1'
  },
})

**Comment by dntzhang** [comment]
@banduoju  非常感谢，修复了

**Comment by dntzhang** [comment]
还有一点小问题，晚点更新下

**Comment by dntzhang** [comment]
是 v2.3.5  https://github.com/Tencent/omi/blob/master/packages/omix/utils/create.js
