### ISSUE TITLE
omi-router运行时报错

### ISSUE THREAD

**Issue by tu3susu** [Tencent/omi#489]
<img width="286" alt="D5066E51-8C51-4850-9610-64F11E3EEEBA" src="https://user-images.githubusercontent.com/42396647/68729322-9ce34f80-0604-11ea-8d77-1bde938776ce.png">
报错如下：
<img width="278" alt="5ED4D892-1EBD-4c92-BF94-247F40FFCC27" src="https://user-images.githubusercontent.com/42396647/68729368-c56b4980-0604-11ea-969b-206969c33aa3.png">

**Comment by dntzhang** [comment]
你不是按照 npm import 的方式使用？ 依赖 path-to-regexp

**Comment by tu3susu** [comment]
是按照  import 使用的，但是没有找到path-to-regexp依赖，npm import 是什么

**Comment by dntzhang** [comment]
我知道，我修复下。

**Comment by tu3susu** [comment]
好的，谢谢了

**Comment by dntzhang** [comment]
由于依赖包 path-to-regexp 版本升级导致的，你升级 omi-router v2.1.0 就可以了。

**Comment by tu3susu** [comment]
好的

**Comment by tu3susu** [comment]
解决了，多谢
