### ISSUE TITLE
页面以及页面组件 use声明数据 改变store中的数据  页面数据视图刷新了  组件没有变化

### ISSUE THREAD

**Issue by MeuJa** [Tencent/omi#495]

**Comment by dntzhang** [comment]
组件是怎么定义的？能搞个简单omix分享链接看下吗？

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/commit/1f8ddd2180023fbccdd607002c0fb827021d750c

验证 ok

**Comment by MEUJIA** [comment]
https://github.com/MEUJIA/miniprogram-lala ，弄了个仓库， meu-submit-cart是用的组件  pages/store/store是页面，原本是想store页面中注册声明改变数据  组件中声明直接使用跟着变化，之前不知道是请求慢还是什么请求成功后改变store的值  连页面都没有拿到改变后的数据，现在改了下，页面给组件传数据能正常使用，还有像页面分享出去进入指定页面，数据就崩了没有之前页面的共享数据，这段时间一直在用它，有这几个疑惑点，求大佬给我指路

**Comment by dntzhang** [comment]
@MEUJIA  看了下你的create.js 是老版本。

**Comment by dntzhang** [comment]
分享出去数据丢失的问题的 omix 无关

**Comment by MEUJIA** [comment]
用的是示例项目的js，==就去更新，  数据不是基于页面吗，A页面数据赋值，B页面使用，当分享进的程序直接进B页面，store的数据不是没得了吗

**Comment by dntzhang** [comment]
分享出去数据要重新拉取一下。不可能会保留的
