### ISSUE TITLE
omi-snap构建生成的文件使用疑问?

### ISSUE THREAD

**Issue by simplefeel** [Tencent/omi#499]
1.首先，我没有使用过Omi框架，对于omi-snap在构建的时候插入html文本以达到在还没有加载chunk之前显示内容提升用户体验的做法是认同的。
2.其次，按照教程build之后的html文件显示如下：
![image](https://user-images.githubusercontent.com/9206408/69206836-d4b04100-0b88-11ea-8f6c-604b03795472.png)
3.现在，问题是：如何在加载完chunk之后隐藏掉index.html里面插入的html文本？

**Comment by dntzhang** [comment]
问题二和三修复了。多谢
```js
render(<my-app />, '#root', store, false, document.querySelector('#root div'))
```
