### ISSUE TITLE
有几个疑问希望能解答下？

### ISSUE THREAD

**Issue by ishowman** [Tencent/omi#504]
1. 除了 https://github.com/Tencent/omi/tree/master/packages/omix#api 这里列举的 api，没有其他 api 了吗？还是说其他 api 和微信小程序的一致？
2. 可以同时支持 ts 和云开发吗？有配置指南吗？
3. 一般情况下，微信小程序的 api 改动几天内你们能实现支持？

**Comment by dntzhang** [comment]
1.其他api和微信小程序一致，create传入的参数会透传给Page或Component构造器
2.没有，但能同时支持
3.有必要会立即实现
