### ISSUE TITLE
为啥只传两个参数给obaa?

### ISSUE THREAD

**Issue by chenzhutian** [Tencent/omi#530]
我注意到在这里 
https://github.com/Tencent/omi/blob/master/packages/omix/utils/create.js#L214
这穿了两个参数给obaa函数, 但是[obaa的定义](https://github.com/Tencent/omi/blob/master/packages/omix/utils/obaa.js#L7)是接收三个参数的(其中第二个是arr).

请问这是怎么回事? 我最近在写typescript的定义, 所以遇到这个问题

**Comment by dntzhang** [comment]
第二个参数是可选，代表需要监听的属性。不传代表监听所有的属性
