### ISSUE TITLE
omi-cli   extend error

### ISSUE THREAD

**Issue by 2008hyt** [Tencent/omi#540]
Attempted import error: 'extend' is not exported from 'omi'.

**Comment by dntzhang** [comment]
Using the  latest version of omi.

**Comment by 2008hyt** [comment]
C:\WINDOWS\system32>npm i omi -g
+ omi@6.17.0
updated 1 package in 5.27s

C:\WINDOWS\system32>omi -v
3.4.16

升级不后还是老版本

**Comment by 2008hyt** [comment]
C:\WINDOWS\system32>npm i omi -g
+ omi@6.17.0
updated 1 package in 5.27s

C:\WINDOWS\system32>omi -v
3.4.16

升级后还是老版本

**Comment by dntzhang** [comment]
omi -v 是查看  omi-cli 的版本
