### ISSUE TITLE
omi 现目前能支持多端小程序么？

### ISSUE THREAD

**Issue by Letyou** [Tencent/omi#548]

**Comment by vicvinc** [comment]
好久不维护了。。

**Comment by dntzhang** [comment]
看提交记录。一直在更新维护 @vicvinc

**Comment by vicvinc** [comment]
@dntzhang

**Comment by vicvinc** [comment]
@dntzhang 

![image](https://user-images.githubusercontent.com/3063949/79061548-deffe280-7cc3-11ea-8879-ec4d9df7f347.png)

sorry，没看主库，看到omix提交都是四月左右的，大佬啥时候更一下TS的库

**Comment by Letyou** [comment]
> _No description provided._
