### ISSUE TITLE
[omix]创建响应式组件没有router问题

### ISSUE THREAD

**Issue by Ammmong123** [Tencent/omi#551]
触发：使用create.Component创建组件
原因：create.Component 获取的this并没有router；所以store.instances[this.route||this.is].push(this)会导致所有响应组件全部push到store.instances['undefine']下；建议this.router可以用this.is
后果：create.Component创建太多组件且store.instances下保存的组件实例不能被销毁；造成性能问题;
同时控制台报错
`Cannot read property 'filter' of undefined; [Component] Lifetime Method Error @ myComponent/chooseArea/index#(anonymous)
TypeError: Cannot read property 'filter' of undefined`

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/commit/d21160c47a2ea5cdfcd50d793aac0f2bab230b43

提交了。试试改成 this.is 之后还不能销毁吗？

**Comment by Ammmong123** [comment]
> [d21160c](https://github.com/Tencent/omi/commit/d21160c47a2ea5cdfcd50d793aac0f2bab230b43)
> 
> 提交了。试试改成 this.is 之后还不能销毁吗？

完美解决啦，感谢大佬
