### ISSUE TITLE
omix: obaa.js中Array.prototype.size=function造成小程序canvas2d组件的touch事件event.touches内存泄露。

### ISSUE THREAD

**Issue by fyuanz** [Tencent/omi#570]
在任意页面使用omix的create方法构造页面，会对任意页面的canvas2d的touch事件产生影响。

event.touches 会将Array.prototype.size方法放入event.thouches中，随着touch事件的触发，event.touches.length无限增加。

更改size为别名(例如Array.prototype.setSize)仍然出现以上情况。

event.touches产生如下数据
```
[
Function,
Function,
Function,
Object,Object
]
```

--------------------------------------------------------------------------------------------------------
不引入omix，在任意页面设置Array.prototype.size = function也会触发此类情况。
怀疑是canvas 2d组件的问题，将追加的原型方法放入touches数组中了？

项目中有使用omix的size方法，请问如何使canvas 2d组件的touch事件与size方法同时使用？

**Comment by fyuanz** [comment]
我不使用size方法了，顺便将size方法从obaa.js中删掉了 :innocent:

**Comment by dntzhang** [comment]
```js
Array.prototype.size = function () {}

// 用以下写法绕过

Object.defineProperty(Array.prototype, 'size', {
	value: function () {},
	enumerable: false,
        configurable: false,
})
```

**Comment by yaoyi601131548** [comment]
> ```js
> Array.prototype.size = function () {}
> 
> // 用以下写法绕过
> 
> Object.defineProperty(Array.prototype, 'size', {
> 	value: function () {},
> 	enumerable: false,
>         configurable: false,
> })
> ```

OK

**Comment by fyuanz** [comment]
OK
