### ISSUE TITLE
x is an ineixst template.

### ISSUE THREAD

**Issue by wei380943047** [Tencent/omi#579]
什么原因？？？ 怎么解决？

**Comment by dntzhang** [comment]
什么框架？什么项目？怎么出现的？

**Comment by 12mmmjkl** [comment]
你好，请问你解决了吗？使用这个命令npx omi-cli init-x my-app
会出现
Omi-Cli is booting... 
Omi-Cli will execute init command... 

Omi-Cli will creating a new omi app in C:\Users\12mmmjkl\WeChatProjects\miniprogram-1\my-app

x is an ineixst template.
Please check on https://github.com/omijs

**Comment by dntzhang** [comment]
直接clone 这个 https://github.com/omijs/template-x
