### ISSUE TITLE
oba vs obaa?

### ISSUE THREAD

**Issue by fehmi** [Tencent/omi#581]
Hello,

Which one is more accurate?

oba (0.1.1): https://github.com/dntzhang/oba/blob/master/oba.js
obaa (2.1.0): https://github.com/Tencent/omi/blob/master/packages/obaa/index.js

Thanks for the goodies

**Comment by dntzhang** [comment]
@fehmi  obaa is  more accurate! please use obaa～

**Comment by fehmi** [comment]
Thank you!
