### ISSUE TITLE
omix地址打不开了？

### ISSUE THREAD

**Issue by Mr-xue** [Tencent/omi#616]
之前是这个地址：https://github.com/Tencent/omi/tree/master/packages/omix
现在怎么打不开了，也找不到对应的仓库

**Comment by yuqing521** [comment]
查看 V6   ##分支中的 omix

**Comment by Mr-xue** [comment]
> 查看 V6分支中的 omix #615
> https://github.com/Tencent/omi/tree/v6/packages/omix

Tks~~
