### ISSUE TITLE
Where is Omix? Has Omix been deprecated? 无法找到 Omix，是否已经废弃？

### ISSUE THREAD

**Issue by bradleyzhou** [Tencent/omi#623]
We discovered that Omix source code has been removed in commit d6f5e69cb8fa5a3ccd0edaa60631e89611d65abf.
From the commit message it seems to be "dead code". Omix is also removed from the README.md of this "omi" project.

But our project depends on Omix to provide a global store in Miniprogram.

Are there any plans to continue Omix? Or should we start look into other store solutions for WeChat Miniprogram?

我们最近才发现 Omix 已经不在本代码库中了，已在 commmit d6f5e69cb8fa5a3ccd0edaa60631e89611d65abf中被移除。在 omi 项目的 README.md 中也已经被删除。
我们的项目用了 Omix。
现在是否要废弃 Omix 这个项目？是不是建议使用其他的 store 解决方案？

**Comment by yuqing521** [comment]
README 及 源码可以查看 V6 分支

**Comment by dntzhang** [comment]
是的，在这里 https://github.com/Tencent/omi/tree/v6

**Comment by NexusLee** [comment]
把我给吓的啊

**Comment by weiyisheng** [comment]
> 是的，在这里 https://github.com/Tencent/omi/tree/v6

请问废弃omix之后，是否有官方的store解决方案，或者是否有对小程序状态管理的设计规划？

**Comment by dntzhang** [comment]
@weiyisheng 关注 westore 这个项目 https://github.com/Tencent/westore ，最近有一些规划设计当中

**Comment by dntzhang** [comment]
westore更新了
