### ISSUE TITLE
Native defining of omi component in browser

### ISSUE THREAD

**Issue by tonis2** [Tencent/omi#69]
Could there rise any problems when defining Omi component with native browser implementation ?

For example i would use `customElements.define('like-button', LikeButton)` 
instead of `define('like-button', LikeButton)` method and just use regular HTML tag instead of `render(h('like-button'), 'body')`.

I can understand that there might come issues with browser compatibility, but could any other problem rise?

Here's example for my question.
https://jsbin.com/zumiday/edit?html,output

**Comment by dntzhang** [comment]
If you do not use the store system, there is no problem.

https://github.com/Tencent/omi/blob/master/packages/omi/src/define.js#L6-L8

Define of omi will calculate component dependent data paths for partial updating.

**Comment by tonis2** [comment]
Thanks, that is all the information i needed.
