### ISSUE TITLE
Consider MobX pluggability

### ISSUE THREAD

**Issue by benjamingr** [Tencent/omi#70]
Consider making MobX pluggable into omi since it's essentially the same kind of reactivity system only except without `Map` `Set` and array goodies.

**Comment by dntzhang** [comment]
The store system is enough.

**Comment by benjamingr** [comment]
@dntzhang the store system does not have features like maps/sets nor array method reactivity. Even if you don't want to support it by default you might want to make another reactivity system pluggable.

**Comment by dntzhang** [comment]
I don't know what reactivity system you want. I think omi's `store system === reactivity system`.

**Comment by dntzhang** [comment]
Pr welcome!

**Comment by devel-pa** [comment]
Hi Guys, do you really need an adapter? As I can connect a Mobx store with ease, like this:
(converted from app starter kit)
```
import {observable} from 'mobx';

export default observable({
    data: { name: 'Omi' },
    rename: function (name) {
        this.data.name = name
    }
});
```

**Comment by dntzhang** [comment]
cool. create new packages(omi-mobx) and pr.

**Comment by dntzhang** [comment]
Or maybe we can use mobx compatible ie11 with the same api.

**Comment by benjamingr** [comment]
> Hi Guys, do you really need an adapter? As I can connect a Mobx store with ease, like this:

This does not maintain cross-store reactivity IIUC - it "hands over" the store

**Comment by dntzhang** [comment]
Fixed~~   @benjamingr @devel-pa  

```js
import { tag, WeElement } from 'omi'
import { observe } from 'omi-mobx'

@observe
@tag('my-app')
class MyApp extends WeElement {

  install() {
    this.data.name = 'omi'
  }

  onClick = () => {
    this.data.name = 'Omi V4.0'
  }

  render(props, data) {
    return (
      <div onClick={this.onClick}>
        <h1 >Welcome to {data.name}</h1>
      </div>
    )
  }
}
```

**Comment by benjamingr** [comment]
Thanks for the fix @dntzhang !
