### ISSUE TITLE
Omi.html   未定义

### ISSUE THREAD

**Issue by canyuegongzi** [Tencent/omi#737]
```
const { define, WeElement, html, render } = Omi
```
![image](https://user-images.githubusercontent.com/32031360/169649698-ccb7836b-e29d-4023-b068-8040a1c33418.png)

**Comment by Muna-Lombe** [comment]
Received with thanks.

**Comment by dntzhang** [comment]
移除了，没有这个api

**Comment by dntzhang** [comment]
自己集成 htm ，不内置到 omi 里

**Comment by canyuegongzi** [comment]
> 自己集成 htm ，不内置到 omi 里

感谢
