### ISSUE TITLE
当自定义的元素接收Object参数时，某些合法数据，正则校验处理有问题，会导致JSON.parse报错

### ISSUE THREAD

**Issue by wangnannanziyu** [Tencent/omi#771]
例如这个对象{"remark":"TEST:12321"}，使用/(['"])?([a-zA-Z0-9_-]+)(['"])?:([^\/])/g进行处理时，会变成'{"remark":""TEST":12321"}'，处理后的对象不再是合法的JSON字符串

**Comment by dntzhang** [comment]
看来只能用 eval 了？

**Comment by dntzhang** [comment]
已处理

**Comment by wangnannanziyu** [comment]
> 已处理

之前就没看懂为啥要加这一段正则处理，现在这样没毛病，用户自己保证传递的JSON字符串必须要合法👍
