### ISSUE TITLE
popup报错 —— v7.0.0-alpha2

### ISSUE THREAD

**Issue by GuYith** [Tencent/omi#868]
omi版本为v6.25.22时popup组件可以正常工作（hover显示气泡），改为v7.0.0-alpha2之后，组件报错，无法正常显示气泡
![image](https://github.com/Tencent/omi/assets/48597370/e616148a-f019-4fa3-80b5-906f144f6d71)

**Comment by dntzhang** [comment]
我看下

**Comment by dntzhang** [comment]
"name": "@omiu/transition",
  "version": "0.0.17",

omiu/transition更新到 0.0.17 试试

**Comment by dntzhang** [comment]
好像还是一样报错。我再看下

**Comment by dntzhang** [comment]
omi更新到 v7.0.0-rc4

**Comment by dntzhang** [comment]
<img width="1501" alt="image" src="https://github.com/Tencent/omi/assets/7917954/5c6c49f7-361e-4633-9958-040cfad24537">

这个例子是ok的

**Comment by dntzhang** [comment]
![image](https://github.com/Tencent/omi/assets/7917954/95cd81a5-51d9-454c-bb22-a607eaebb94f)
这个例子是可以的
