### ISSUE TITLE
打包之后，props失效

### ISSUE THREAD

**Issue by WaterAndBin** [Tencent/omi#917]
您好，其实我是初学者，非常抱歉打扰到您了。我在用Omi独立开发组件的时候，打包之后在vue中使用，发现props跟children在那边无法正常识别到，我尝试输出props，得到的结果都是 {css=[]}，我并不是很明白这是为什么？可能是我的打包方式有问题，因此想请教您如何打包。
这是vite.config.ts
![image](https://github.com/user-attachments/assets/69c68e0a-19bd-4528-ab34-c58afafa731c)
这是index.ts的代码
`export * from "./buttom";`
这是button.tsx的代码
`import { tag, h, WeElement } from "omi";

@tag("t-button")
export default class Button extends WeElement {
  static css = [];

  render(props: any) {
    console.log(props);
    const { children, msg } = props;

    return (
      <div>
        <button>
          hallo,{msg},{children},!!!
        </button>
      </div>
    );
  }
}`
若在button.tsx里面用render(<hello-omi msg='Omi' />, 'body')这些代码，都是正常运行的，我不是很明白是vue的问题还是我打包方式的问题，希望您能给予答复，非常感谢

**Comment by wjcheng20** [comment]
可以加上 static propTypes试试。

**Comment by WaterAndBin** [comment]
> 可以加上 static propTypes试试。

非常感谢大佬，呜呜呜
