### ISSUE TITLE
关于omi的一些疑问

### ISSUE THREAD

**Issue by ShanaMaid** [Tencent/omi#94]
看文档omi是基于shadow dom机械能实现的，比较好奇以下问题：
- omi在鹅厂内部的项目使用覆盖率如何？
- omi和react、vue、ng相比性能上如何？

感谢作者对开源项目的贡献！best wish!

**Comment by dntzhang** [comment]
多谢关注，等性能报告，preact性能很好，omi就不会差

**Comment by ShanaMaid** [comment]
@dntzhang 鹅厂内部使用情况如何呢？

**Comment by dntzhang** [comment]
还没去统计，不过还多部门来找我们要 UI 框架了。我们正在全力赶这个项目 https://github.com/Tencent/omi/tree/master/packages/omi-element-ui

**Comment by ShanaMaid** [comment]
thx!
