### ISSUE TITLE
是否考虑支持组件render返回数组呢

### ISSUE THREAD

**Issue by 1921622004** [Tencent/omi#95]
我在这边写了一下，简单的测试一下没什么大问题

**Comment by dntzhang** [comment]
想支持，欢迎pr

**Comment by dntzhang** [comment]
Uncaught DOMException: Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.
    at HTMLElement.connectedCallback (http://127.0.0.1:5500/packages/omi/examples/render-array/b.js:1047:29)
    at http://127.0.0.1:5500/packages/omi/examples/render-array/b.js:361:22
    at Array.forEach (<anonymous>)
    at diff (http://127.0.0.1:5500/packages/omi/examples/render-array/b.js:359:13)
    at HTMLElement.update (http://127.0.0.1:5500/packages/omi/examples/render-array/b.js:1084:7)
    at http://127.0.0.1:5500/packages/omi/examples/render-array/b.js:1469:16

**Comment by dntzhang** [comment]
```js
import { tag, render, WeElement } from '../../src/omi'

@tag('hello-element')
class HelloElement extends WeElement {
  render() {
    return [<div>Hello</div>, <div>Element</div>]
  }
}

@tag('my-app')
class MyApp extends WeElement {
  render() {
    return [<hello-element />, <hello-element />, <div>abc</div>]
	}

	installed(){
		setTimeout(()=>{
			this.update()
		},1000)
	}
}

render(<my-app />, 'body')
```

**Comment by dntzhang** [comment]
render 数组，update 会出错~

**Comment by 1921622004** [comment]
我晚上回去看下。

**Comment by 1921622004** [comment]
修改了一下，测试的例子也改了，问题出在每次update都会重新挂载，触发connectedCallback，之前我测试的时候没发现这个问题。如果发现什么问题联系我。

**Comment by dntzhang** [comment]
赞，明天等我把var改成let就完美了
